### ISSUE TITLE
Page previews on staging are broken

### ISSUE THREAD

**Issue by alanmoo** [mozilla/foundation.mozilla.org#2340]
Hitting "Preview" on a staging page results in a 500 error.

**Comment by cadecairos** [comment]
Just got this on our radar. we'll investigate.

**Comment by cadecairos** [comment]
@alanmoo Is this still a problem? If so, can you provide detailed STR?

**Comment by alanmoo** [comment]
1.) Visit the edit view for a page on staging. For example, https://foundation.mofostaging.net/cms/pages/223/edit/
2.) Click the "preview" button at the bottom.
3.) Observe 500 error.

**Comment by cadecairos** [comment]
This looks like an issue in `wagtailmetadata`. I have a stacktrace, but still trying to repro locally.

**Comment by cadecairos** [comment]
It appears that this was fixed by updating the domain name listed in the Site record on staging. I'm going to check to see if the copy script isn't working as expected.

**Comment by cadecairos** [comment]
This issue [_should_ have been prevented by this part of the cleanup script](https://github.com/MozillaFoundation/mofo-cron/blob/61d48da45c13d8b2101f2d32c3f804dd9d87f6ed/tasks/clone_foundation_site/cleanup.sql#L21-L24), but appears to have not happened. I'm going to check on Monday if it successfully ran or not.

**Comment by cadecairos** [comment]
This is definitely not fixed. I'm going to try reorganizing the cleanup SQL script to see if something is silently failing.

**Comment by cadecairos** [comment]
```
2019-01-16T16:39:35.130159+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/django/template/base.py", line 990, in render
2019-01-16T16:39:35.130160+00:00 app[web.1]: bit = node.render_annotated(context)
2019-01-16T16:39:35.130162+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/django/template/base.py", line 957, in render_annotated
2019-01-16T16:39:35.130163+00:00 app[web.1]: return self.render(context)
2019-01-16T16:39:35.130165+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/django/template/loader_tags.py", line 177, in render
2019-01-16T16:39:35.130166+00:00 app[web.1]: return compiled_parent._render(context)
2019-01-16T16:39:35.130168+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/django/template/base.py", line 199, in _render
2019-01-16T16:39:35.130169+00:00 app[web.1]: return self.nodelist.render(context)
2019-01-16T16:39:35.130171+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/django/template/base.py", line 990, in render
2019-01-16T16:39:35.130172+00:00 app[web.1]: bit = node.render_annotated(context)
2019-01-16T16:39:35.130174+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/django/template/base.py", line 957, in render_annotated
2019-01-16T16:39:35.130175+00:00 app[web.1]: return self.render(context)
2019-01-16T16:39:35.130177+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/django/template/loader_tags.py", line 177, in render
2019-01-16T16:39:35.130178+00:00 app[web.1]: return compiled_parent._render(context)
2019-01-16T16:39:35.130180+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/django/template/base.py", line 199, in _render
2019-01-16T16:39:35.130182+00:00 app[web.1]: return self.nodelist.render(context)
2019-01-16T16:39:35.130183+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/django/template/base.py", line 990, in render
2019-01-16T16:39:35.130185+00:00 app[web.1]: bit = node.render_annotated(context)
2019-01-16T16:39:35.130186+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/django/template/base.py", line 957, in render_annotated
2019-01-16T16:39:35.130188+00:00 app[web.1]: return self.render(context)
2019-01-16T16:39:35.130190+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/django/template/loader_tags.py", line 72, in render
2019-01-16T16:39:35.130191+00:00 app[web.1]: result = block.nodelist.render(context)
2019-01-16T16:39:35.130193+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/django/template/base.py", line 990, in render
2019-01-16T16:39:35.130194+00:00 app[web.1]: bit = node.render_annotated(context)
2019-01-16T16:39:35.130196+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/django/template/base.py", line 957, in render_annotated
2019-01-16T16:39:35.130198+00:00 app[web.1]: return self.render(context)
2019-01-16T16:39:35.130199+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/django/template/library.py", line 203, in render
2019-01-16T16:39:35.130201+00:00 app[web.1]: output = self.func(*resolved_args, **resolved_kwargs)
2019-01-16T16:39:35.130210+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/wagtailmetadata/templatetags/wagtailmetadata_tags.py", line 14, in meta_tags
2019-01-16T16:39:35.130212+00:00 app[web.1]: return tags.meta_tags(request, model)
2019-01-16T16:39:35.130213+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/wagtailmetadata/tags.py", line 14, in meta_tags
2019-01-16T16:39:35.130215+00:00 app[web.1]: 'site_name': request.site.site_name,
2019-01-16T16:39:35.130216+00:00 app[web.1]: AttributeError: 'WSGIRequest' object has no attribute 'site'
2019-01-16T16:39:35.176179+00:00 app[web.1]: 10.111.196.146 - - [16/Jan/2019:16:39:35 +0000] 
2019-01-16T16:39:38.568689+00:00 app[web.1]: Traceback (most recent call last):
2019-01-16T16:39:38.568692+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
2019-01-16T16:39:38.568694+00:00 app[web.1]: response = get_response(request)
2019-01-16T16:39:38.568696+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/django/core/handlers/base.py", line 217, in _get_response
2019-01-16T16:39:38.568711+00:00 app[web.1]: response = self.process_exception_by_middleware(e, request)
2019-01-16T16:39:38.568716+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/django/core/handlers/base.py", line 215, in _get_response
2019-01-16T16:39:38.568718+00:00 app[web.1]: response = response.render()
2019-01-16T16:39:38.568720+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/django/template/response.py", line 107, in render
2019-01-16T16:39:38.568721+00:00 app[web.1]: self.content = self.rendered_content
2019-01-16T16:39:38.568723+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/django/template/response.py", line 84, in rendered_content
2019-01-16T16:39:38.568724+00:00 app[web.1]: content = template.render(context, self._request)
2019-01-16T16:39:38.568726+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/django/template/backends/django.py", line 66, in render
2019-01-16T16:39:38.568727+00:00 app[web.1]: return self.template.render(context)
2019-01-16T16:39:38.568729+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/django/template/base.py", line 207, in render
2019-01-16T16:39:38.568731+00:00 app[web.1]: return self._render(context)
2019-01-16T16:39:38.568732+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/django/template/base.py", line 199, in _render
2019-01-16T16:39:38.568734+00:00 app[web.1]: return self.nodelist.render(context)
2019-01-16T16:39:38.568736+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/django/template/base.py", line 990, in render
2019-01-16T16:39:38.568737+00:00 app[web.1]: bit = node.render_annotated(context)
2019-01-16T16:39:38.568739+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/django/template/base.py", line 957, in render_annotated
2019-01-16T16:39:38.568741+00:00 app[web.1]: return self.render(context)
2019-01-16T16:39:38.568742+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/django/template/loader_tags.py", line 177, in render
2019-01-16T16:39:38.568744+00:00 app[web.1]: return compiled_parent._render(context)
2019-01-16T16:39:38.568745+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/django/template/base.py", line 199, in _render
2019-01-16T16:39:38.568747+00:00 app[web.1]: return self.nodelist.render(context)
2019-01-16T16:39:38.568749+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/django/template/base.py", line 990, in render
2019-01-16T16:39:38.568751+00:00 app[web.1]: bit = node.render_annotated(context)
2019-01-16T16:39:38.568752+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/django/template/base.py", line 957, in render_annotated
2019-01-16T16:39:38.568754+00:00 app[web.1]: return self.render(context)
2019-01-16T16:39:38.568755+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/django/template/loader_tags.py", line 177, in render
2019-01-16T16:39:38.568757+00:00 app[web.1]: return compiled_parent._render(context)
2019-01-16T16:39:38.568759+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/django/template/base.py", line 199, in _render
2019-01-16T16:39:38.568760+00:00 app[web.1]: return self.nodelist.render(context)
2019-01-16T16:39:38.568762+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/django/template/base.py", line 990, in render
2019-01-16T16:39:38.568764+00:00 app[web.1]: bit = node.render_annotated(context)
2019-01-16T16:39:38.568765+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/django/template/base.py", line 957, in render_annotated
2019-01-16T16:39:38.568767+00:00 app[web.1]: return self.render(context)
2019-01-16T16:39:38.568768+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/django/template/loader_tags.py", line 177, in render
2019-01-16T16:39:38.568770+00:00 app[web.1]: return compiled_parent._render(context)
2019-01-16T16:39:38.568771+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/django/template/base.py", line 199, in _render
2019-01-16T16:39:38.568773+00:00 app[web.1]: return self.nodelist.render(context)
2019-01-16T16:39:38.568774+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/django/template/base.py", line 990, in render
2019-01-16T16:39:38.568776+00:00 app[web.1]: bit = node.render_annotated(context)
2019-01-16T16:39:38.568777+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/django/template/base.py", line 957, in render_annotated
2019-01-16T16:39:38.568779+00:00 app[web.1]: return self.render(context)
2019-01-16T16:39:38.568780+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/django/template/loader_tags.py", line 72, in render
2019-01-16T16:39:38.568782+00:00 app[web.1]: result = block.nodelist.render(context)
2019-01-16T16:39:38.568784+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/django/template/base.py", line 990, in render
2019-01-16T16:39:38.568785+00:00 app[web.1]: bit = node.render_annotated(context)
2019-01-16T16:39:38.568787+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/django/template/base.py", line 957, in render_annotated
2019-01-16T16:39:38.568789+00:00 app[web.1]: return self.render(context)
2019-01-16T16:39:38.568791+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/django/template/library.py", line 203, in render
2019-01-16T16:39:38.568792+00:00 app[web.1]: output = self.func(*resolved_args, **resolved_kwargs)
2019-01-16T16:39:38.568802+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/wagtailmetadata/templatetags/wagtailmetadata_tags.py", line 14, in meta_tags
2019-01-16T16:39:38.568803+00:00 app[web.1]: return tags.meta_tags(request, model)
2019-01-16T16:39:38.568805+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/wagtailmetadata/tags.py", line 14, in meta_tags
2019-01-16T16:39:38.568806+00:00 app[web.1]: 'site_name': request.site.site_name,
2019-01-16T16:39:38.568808+00:00 app[web.1]: AttributeError: 'WSGIRequest' object has no attribute 'site'

```

**Comment by cadecairos** [comment]
Possible lead: load_fake_data overriding.
