### ISSUE TITLE
Buyers guide: KeyError: 'draft' on prod

### ISSUE THREAD

**Issue by patjouk** [mozilla/foundation.mozilla.org#2529]
I had to rollback prod after deploying those commits: https://github.com/mozilla/foundation.mozilla.org/compare/4ab2a99c...71edc283

Traceback:
```
2019-01-28T15:59:32.478362+00:00 app[web.1]: Internal Server Error: /en/privacynotincluded/
2019-01-28T15:59:32.478384+00:00 app[web.1]: Traceback (most recent call last):
2019-01-28T15:59:32.478392+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
2019-01-28T15:59:32.478394+00:00 app[web.1]: response = get_response(request)
2019-01-28T15:59:32.478401+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
2019-01-28T15:59:32.478404+00:00 app[web.1]: response = self.process_exception_by_middleware(e, request)
2019-01-28T15:59:32.478406+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
2019-01-28T15:59:32.478408+00:00 app[web.1]: response = wrapped_callback(request, *callback_args, **callback_kwargs)
2019-01-28T15:59:32.478410+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/contextlib.py", line 52, in inner
2019-01-28T15:59:32.478413+00:00 app[web.1]: return func(*args, **kwds)
2019-01-28T15:59:32.478415+00:00 app[web.1]: File "/app/network-api/networkapi/buyersguide/views.py", line 58, in check_locale
2019-01-28T15:59:32.478417+00:00 app[web.1]: return view_handler(*args, **kwargs)
2019-01-28T15:59:32.478418+00:00 app[web.1]: File "/app/network-api/networkapi/buyersguide/views.py", line 84, in buyersguide_home
2019-01-28T15:59:32.478420+00:00 app[web.1]: 'mediaUrl': MEDIA_URL,
2019-01-28T15:59:32.478422+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/django/shortcuts.py", line 30, in render
2019-01-28T15:59:32.478423+00:00 app[web.1]: content = loader.render_to_string(template_name, context, request, using=using)
2019-01-28T15:59:32.478425+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/django/template/loader.py", line 68, in render_to_string
2019-01-28T15:59:32.478426+00:00 app[web.1]: return template.render(context, request)
2019-01-28T15:59:32.478428+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/django/template/backends/django.py", line 66, in render
2019-01-28T15:59:32.478429+00:00 app[web.1]: return self.template.render(context)
2019-01-28T15:59:32.478431+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/django/template/base.py", line 207, in render
2019-01-28T15:59:32.478432+00:00 app[web.1]: return self._render(context)
2019-01-28T15:59:32.478434+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/django/template/base.py", line 199, in _render
2019-01-28T15:59:32.478435+00:00 app[web.1]: return self.nodelist.render(context)
2019-01-28T15:59:32.478437+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/django/template/base.py", line 990, in render
2019-01-28T15:59:32.478438+00:00 app[web.1]: bit = node.render_annotated(context)
2019-01-28T15:59:32.478440+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/django/template/base.py", line 957, in render_annotated
2019-01-28T15:59:32.478442+00:00 app[web.1]: return self.render(context)
2019-01-28T15:59:32.478443+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/django/template/loader_tags.py", line 177, in render
2019-01-28T15:59:32.478445+00:00 app[web.1]: return compiled_parent._render(context)
2019-01-28T15:59:32.478446+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/django/template/base.py", line 199, in _render
2019-01-28T15:59:32.478448+00:00 app[web.1]: return self.nodelist.render(context)
2019-01-28T15:59:32.478449+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/django/template/base.py", line 990, in render
2019-01-28T15:59:32.478451+00:00 app[web.1]: bit = node.render_annotated(context)
2019-01-28T15:59:32.478452+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/django/template/base.py", line 957, in render_annotated
2019-01-28T15:59:32.478454+00:00 app[web.1]: return self.render(context)
2019-01-28T15:59:32.478455+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/django/template/loader_tags.py", line 72, in render
2019-01-28T15:59:32.478457+00:00 app[web.1]: result = block.nodelist.render(context)
2019-01-28T15:59:32.478458+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/django/template/base.py", line 990, in render
2019-01-28T15:59:32.478460+00:00 app[web.1]: bit = node.render_annotated(context)
2019-01-28T15:59:32.478461+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/django/template/base.py", line 957, in render_annotated
2019-01-28T15:59:32.478463+00:00 app[web.1]: return self.render(context)
2019-01-28T15:59:32.478465+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/django/template/defaulttags.py", line 172, in render
2019-01-28T15:59:32.478466+00:00 app[web.1]: values = list(values)
2019-01-28T15:59:32.478468+00:00 app[web.1]: File "/app/network-api/networkapi/buyersguide/views.py", line 67, in <lambda>
2019-01-28T15:59:32.478469+00:00 app[web.1]: return filter(lambda p: p['draft'] is False, products)
2019-01-28T15:59:32.478471+00:00 app[web.1]: KeyError: 'draft'
```

Looks like the bug is from this PR: https://github.com/mozilla/foundation.mozilla.org/pull/2439 @Pomax 
It was only spotted on prod and it's not currently happening on staging or newest review apps.

**Comment by Pomax** [comment]
Inspecting the production database shows this as last entry in the `django_migrations` table:

```
320 | buyersguide      | 0018_product_is_draft                                   | 2019-01-28 15:29:54.939208+00
```

Which suggests that the `buyersguide_product` table schema is in sync with `master`. However, inspecting the `buyersguide_product` table shows the following schema instead:

```
 id |               name               |     company     |                                                                                                                                                                                                                                                                                                                                                 blurb                                                                                                                                                                                                                                                                                                                                                  |                                                                url                                                                |             price              |                                         image                                         | location_device | delete_data | share_data | child_rules |                                                                                                                                                                                  worst_case                                                                                                                                                                                  |                                           email                                           |                                              live_chat                                               | manage_security | must_change_default_password |          phone_number           | security_updates | uses_encryption | camera_app | camera_device | child_rules_helptext |                                                                                                                                                                                                                                        delete_data_helptext                                                                                                                                                                                                                                         | location_app |                                                                                                       manage_security_helptext                                                                                                       | microphone_app | microphone_device |                                                                                                        must_change_default_password_helptext                                                                                                        |                              privacy_policy_helptext                              |                  security_updates_helptext                   |                                                                                                                                                                                                                                                                                                                                                                           share_data_helptext                                                                                                                                                                                                                                                                                                                                                                           |                                                                                                                      uses_encryption_helptext                                                                                                                      | meets_minimum_security_standards | privacy_policy_reading_level |                            privacy_policy_url                            |     twitter     |               slug               |                       privacy_policy_reading_level_url                        |                                                       cloudinary_image                                                        | draft
```
That is: there is no `draft` property in it.

I don't know _how_ this could have happened, but it does mean that Django will go "there are no migrations to apply, this db is already up to date" when in fact the `buyersguide_product` table is not up to date at all.

It might be necessary to drop that migration entry id=320 from the `django_migrations` table, so that django knows it still needs to apply it during release.

**Comment by Pomax** [comment]
Interesting detail that might be relevant here, or might be completely unrelated: staging seems to be using postgres 10.6, whereas production seems to be using postgres 9.6 still.

**Comment by Pomax** [comment]
@patjouk @cadecairos a thought occurs... we use a cache for the PNI products, do we _clear_ that cache on a redeploy? If not, then seeing things error out would make a lot of sense, where the new code, with the up to date db, _bypasses the real db_ and instead just uses the old, incompatible, cache data.

**Comment by Pomax** [comment]
Redeploying to prod broke things for unauthorized users until I cleared the cache, so it looks like the problem is that we don't clear the cache during `release-steps.sh` - filed as https://github.com/mozilla/foundation.mozilla.org/issues/2532
