### ISSUE TITLE
CI is failing _a lot_

### ISSUE THREAD

**Issue by Pomax** [mozilla/foundation.mozilla.org#2594]
There's a lot of CI failure happening recently, so I figured I'd file this with some logs so we have something to look at @alanmoo @cadecairos @patjouk 

Travis failures:
```
Post-processed 'wagtailadmin/css/normalize.css' as 'wagtailadmin/css/normalize.aa75c284e281.css'
Post-processed 'wagtailadmin/css/core.css' as 'wagtailadmin/css/core.27ba9a2168bf.css'
Post-processed 'wagtailadmin/css/userbar.css' as 'wagtailadmin/css/userbar.15d766f7de4f.css'
Post-processed 'wagtailstyleguide/css/styleguide.css' as 'wagtailstyleguide/css/styleguide.917c29e92d5d.css'
Post-processed 'wagtailmodeladmin/css/index.css' as 'wagtailmodeladmin/css/index.73ce0bf177ce.css'
Post-processed 'wagtailmodeladmin/css/choose_parent_page.css' as 'wagtailmodeladmin/css/choose_parent_page.408cbfc7829f.css'
Post-processed 'rest_framework/css/prettify.css' as 'rest_framework/css/prettify.a987f72342ee.css'
Post-processed 'rest_framework/css/bootstrap-theme.min.css' as 'rest_framework/css/bootstrap-theme.min.66b84a04375e.css'
Post-processed 'rest_framework/css/default.css' as 'rest_framework/css/default.8d5591a6aabc.css'
Post-processed 'rest_framework/css/bootstrap.min.css' as 'rest_framework/css/bootstrap.min.77017a69879a.css'
Post-processed 'rest_framework/css/bootstrap-tweaks.css' as 'rest_framework/css/bootstrap-tweaks.46ed116b0edd.css'
Post-processed 'rest_framework/css/bootstrap-theme.css' as 'rest_framework/css/bootstrap-theme.a279820bbeb5.css'
Post-processed 'rest_framework/css/font-awesome-4.0.3.css' as 'rest_framework/css/font-awesome-4.0.3.c1e1ea213abf.css'
Post-processed 'rest_framework/css/bootstrap.css' as 'rest_framework/css/bootstrap.23773f1bb199.css'
Post-processed 'adminsortable/css/admin.sortable.css' as 'adminsortable/css/admin.sortable.82662a72ea4a.css'
Post-processed 'adminsortable/css/admin.sortable.inline.css' as 'adminsortable/css/admin.sortable.inline.5fa61b0bf660.css'
Post-processed 'wagtail_modeltranslation/css/page_editor_modeltranslation.css' as 'wagtail_modeltranslation/css/page_editor_modeltranslation.d1040dbcc12f.css'
Post-processed 'css/language_toggles.css' as 'css/language_toggles.4e5fd85cfa6b.css'
Post-processed 'wagtailadmin/css/vendor/jquery-ui/jquery-ui-1.10.3.verdant.css' as 'wagtailadmin/css/vendor/jquery-ui/jquery-ui-1.10.3.verdant.767104e7b415.css'
Post-processed 'wagtailadmin/css/layouts/404-additionals.css' as 'wagtailadmin/css/layouts/404-additionals.f2073c8d410a.css'
Post-processed 'wagtailimages/css/vendor/jquery.Jcrop.min.css' as 'wagtailimages/css/vendor/jquery.Jcrop.min.a24cf7249c09.css'
Post-processed 'wagtailadmin/css/vendor/jquery.tagit.css' as 'wagtailadmin/css/vendor/jquery.tagit.1060b2909c82.css'
Post-processed 'wagtailadmin/css/vendor/tagit.ui-zendesk.css' as 'wagtailadmin/css/vendor/tagit.ui-zendesk.aa48f0315498.css'
Post-processed 'wagtailadmin/css/layouts/home.css' as 'wagtailadmin/css/layouts/home.5464b4fbaa8f.css'
Post-processed 'wagtailadmin/css/layouts/404.css' as 'wagtailadmin/css/layouts/404.7516958b06be.css'
Post-processed 'wagtailadmin/css/layouts/login.css' as 'wagtailadmin/css/layouts/login.ea7b231e7652.css'
Post-processed 'wagtailadmin/css/layouts/page-editor.css' as 'wagtailadmin/css/layouts/page-editor.0aaea2042304.css'
Post-proces/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/environ/environ.py:630: UserWarning: /home/travis/build/mozilla/foundation.mozilla.org/network-api/networkapi/.env doesn't exist - if you're not configuring your environment separately, create one.
  "environment separately, create one." % env_file)
Traceback (most recent call last):
  File "network-api/manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 199, in handle
    collected = self.collect()
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 148, in collect
    (original_path, processed_path), level=1)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 224, in log
    self.stdout.write(msg)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/django/core/management/base.py", line 110, in write
    self._out.write(force_str(style_func(msg)))
BlockingIOError: [Errno 11] write could not complete without blocking
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='UTF-8'>
BlockingIOError: [Errno 11] write could not complete without blocking
The command "pipenv run python network-api/manage.py collectstatic --no-input" failed and exited with 120 during .
```

Appveyor failures:
```
python -m pip install pipenv
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
Collecting pipenv
  Downloading https://files.pythonhosted.org/packages/bb/15/b155a5c0d19ce41609f50bb70a37e0de092b453ec4bd2eac59e53a2c3227/pipenv-2018.11.26-py2-none-any.whl (5.2MB)
Requirement already satisfied: pip>=9.0.1 in c:\python27\lib\site-packages (from pipenv) (19.0.1)
Requirement already satisfied: virtualenv in c:\python27\lib\site-packages (from pipenv) (13.1.2)
Collecting enum34; python_version < "3" (from pipenv)
  Downloading https://files.pythonhosted.org/packages/c5/db/e56e6b4bbac7c4a06de1c50de6fe1ef3810018ae11732a50f15f62c7d050/enum34-1.1.6-py2-none-any.whl
Requirement already satisfied: setuptools>=36.2.1 in c:\python27\lib\site-packages (from pipenv) (39.0.1)
Collecting typing; python_version < "3.5" (from pipenv)
  Downloading https://files.pythonhosted.org/packages/cc/3e/29f92b7aeda5b078c86d14f550bf85cff809042e3429ace7af6193c3bc9f/typing-3.6.6-py2-none-any.whl
Collecting virtualenv-clone>=0.2.5 (from pipenv)
  Downloading https://files.pythonhosted.org/packages/e3/d9/d9c56deb483c4d3289a00b12046e41428be64e8236fa210111a1f57cc42d/virtualenv_clone-0.5.1-py2.py3-none-any.whl
Collecting certifi (from pipenv)
  Downloading https://files.pythonhosted.org/packages/9f/e0/accfc1b56b57e9750eba272e24c4dddeac86852c2bebd1236674d7887e8a/certifi-2018.11.29-py2.py3-none-any.whl (154kB)
Installing collected packages: enum34, typing, virtualenv-clone, certifi, pipenv
Successfully installed certifi-2018.11.29 enum34-1.1.6 pipenv-2018.11.26 typing-3.6.6 virtualenv-clone-0.5.1
python -m pipenv install --dev --deploy
Creating a virtualenv for this project...
Pipfile: C:\projects\network\Pipfile
Using C:/Python36-x64/python.exe (3.6.6) to create virtualenv...
Running virtualenv with interpreter C:/Python36-x64/python.exe
FAIL
['Traceback (most recent call last):\n', '  File "C:\\Python27\\lib\\site-packages\\pipenv\\utils.py", line 501, in create_spinner\n    yield sp\n', '  File "C:\\Python27\\lib\\site-packages\\pipenv\\core.py", line 935, in do_create_virtualenv\n    extra=[crayons.blue("{0}".format(c.err)),]\n', 'VirtualenvCreationException: Failed to create virtual environment.\n']
[pipenv.exceptions.VirtualenvCreationException]:   File "C:\Python27\lib\site-packages\pipenv\cli\command.py", line 254, in install
[pipenv.exceptions.VirtualenvCreationException]:       editable_packages=state.installstate.editables,
[pipenv.exceptions.VirtualenvCreationException]:   File "C:\Python27\lib\site-packages\pipenv\core.py", line 1741, in do_install
[pipenv.exceptions.VirtualenvCreationException]:       pypi_mirror=pypi_mirror,
[pipenv.exceptions.VirtualenvCreationException]:   File "C:\Python27\lib\site-packages\pipenv\core.py", line 574, in ensure_project
[pipenv.exceptions.VirtualenvCreationException]:       pypi_mirror=pypi_mirror,
[pipenv.exceptions.VirtualenvCreationException]:   File "C:\Python27\lib\site-packages\pipenv\core.py", line 506, in ensure_virtualenv
[pipenv.exceptions.VirtualenvCreationException]:       python=python, site_packages=site_packages, pypi_mirror=pypi_mirror
[pipenv.exceptions.VirtualenvCreationException]:   File "C:\Python27\lib\site-packages\pipenv\core.py", line 935, in do_create_virtualenv
[pipenv.exceptions.VirtualenvCreationException]:       extra=[crayons.blue("{0}".format(c.err)),]
[pipenv.exceptions.VirtualenvCreationException]: Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\virtualenv.py", line 8, in <module>
    import base64
  File "C:\Python36-x64\lib\base64.py", line 9, in <module>
    import re
  File "C:\Python36-x64\lib\re.py", line 142, in <module>
    class RegexFlag(enum.IntFlag):
AttributeError: module 'enum' has no attribute 'IntFlag'
Failed to create virtual environment.
Command exited with code 1
```

**Comment by Pomax** [comment]
The travis one is particularly crazy because `.travis.yml` actually uses python in its pre-install section to turn _off_ nonblocking IO on stdout...

**Comment by Pomax** [comment]
Appveyor looks like it's actually a venv error? It also looks like it's using Python 2.7 which is probably not the version it should be using at all.

**Comment by youriwims** [comment]
I'm getting the same Travis error as Pomax for #2600.

**Comment by mmmavis** [comment]
Restarting usually would solve the issue but yes, I've been getting the same errors lately as well.

**Comment by Pomax** [comment]
https://github.com/travis-ci/travis-ci/issues/4704 had a fix to disable non_blocking stdout, so I added it to https://github.com/mozilla/foundation.mozilla.org/pull/2617/files#diff-354f30a63fb0907d4ad57269548329e3R7 and despite a few updates and rebases, I've not seen that fail CI anymore, so... that feels encouraging.

**Comment by patjouk** [comment]
I didn't see that error again so I'm closing this ticket 🎉
