### ISSUE TITLE
wagtail-modeltranslation breaks load_fake_data --delete

### ISSUE THREAD

**Issue by Pomax** [mozilla/foundation.mozilla.org#2616]
We're having `flush_models.py` run a page clear:
```
        self.stdout.write('Dropping all Pages')
        Page.objects.exclude(title='Root').delete()
```
However, that does not seem to leave the right page intact. `load_fake_data --delete` run log:
```
Dropping Image objects...
Dropping Highlight objects...
Dropping News objects...
Dropping Milestone objects...
Dropping Person objects...
Dropping InternetHealthIssue objects...
Dropping Affiliation objects...
Dropping Wagtail CTAs...
Dropping all Pages
Traceback (most recent call last):
  File "network-api\manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "C:\Users\Mike\.virtualenvs\foundation.mozilla.org-4aDC7Y6j\lib\site-packages\django\core\management\__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "C:\Users\Mike\.virtualenvs\foundation.mozilla.org-4aDC7Y6j\lib\site-packages\django\core\management\__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\Users\Mike\.virtualenvs\foundation.mozilla.org-4aDC7Y6j\lib\site-packages\django\core\management\base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "C:\Users\Mike\.virtualenvs\foundation.mozilla.org-4aDC7Y6j\lib\site-packages\django\core\management\base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "C:\Users\Mike\Documents\Git\collaborations\mozilla\foundation.mozilla.org\network-api\networkapi\management\commands\load_fake_data.py", line 108, in handle
    call_command('flush_models')
  File "C:\Users\Mike\.virtualenvs\foundation.mozilla.org-4aDC7Y6j\lib\site-packages\django\core\management\__init__.py", line 131, in call_command
    return command.execute(*args, **defaults)
  File "C:\Users\Mike\.virtualenvs\foundation.mozilla.org-4aDC7Y6j\lib\site-packages\django\core\management\base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "C:\Users\Mike\Documents\Git\collaborations\mozilla\foundation.mozilla.org\network-api\networkapi\management\commands\flush_models.py", line 51, in handle
    Page.objects.exclude(title='Root').exclude(id=1).delete()
  File "C:\Users\Mike\.virtualenvs\foundation.mozilla.org-4aDC7Y6j\lib\site-packages\treebeard\mp_tree.py", line 116, in delete
    parent.save()
  File "C:\Program Files\Python36\Lib\contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "C:\Users\Mike\.virtualenvs\foundation.mozilla.org-4aDC7Y6j\lib\site-packages\wagtail_modeltranslation\patch_wagtailadmin.py", line 531, in __call__
    result = self.func(instance, *args, **kwargs)
  File "C:\Program Files\Python36\Lib\contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "C:\Users\Mike\.virtualenvs\foundation.mozilla.org-4aDC7Y6j\lib\site-packages\wagtail\core\models.py", line 442, in save
    self.full_clean()
  File "C:\Users\Mike\.virtualenvs\foundation.mozilla.org-4aDC7Y6j\lib\site-packages\wagtail\core\models.py", line 432, in full_clean
    super().full_clean(*args, **kwargs)
  File "C:\Users\Mike\.virtualenvs\foundation.mozilla.org-4aDC7Y6j\lib\site-packages\django\db\models\base.py", line 1250, in full_clean
    raise ValidationError(errors)
django.core.exceptions.ValidationError: {'title': ['This field cannot be blank.'], 'title_en': ['This field cannot be blank.'], 'slug': ['This field cannot be blank.'], 'slug_en': ['This field cannot be blank.']}
```
A workaround is to manually delete db.sqlite3 + `inv migrate` + `manage load_fake_data`, but let's see if we can make the `--delete` flag work properly again.

**Comment by cadecairos** [comment]
@Pomax is this still happening? even after the changes made [here](https://github.com/mozilla/foundation.mozilla.org/pull/2581)

**Comment by Pomax** [comment]
testing to see if this is still happening.

**Comment by Pomax** [comment]
https://github.com/mozilla/foundation.mozilla.org/pull/2581 fixed this.
