### ISSUE TITLE
Visiting the help page on the foundation site return a 5xx

### ISSUE THREAD

**Issue by patjouk** [mozilla/foundation.mozilla.org#3556]
**Describe the bug**
the `help` page is a page for dev and available on review apps. Visiting `https://foundation.mozilla.org/help/` will return a 5xx.

**To Reproduce**
1. Go to https://foundation.mozilla.org/help/

**Expected behavior**
Redirect to the foundation homepage.

**Additional context**
Traceback:
```
 14:44:55.281 foundation.mozilla.org logplex <190>1 2019-08-20T12:44:54.963872+00:00 host app web.1 - Internal Server Error: /help/
14:44:55.282 foundation.mozilla.org logplex <190>1 2019-08-20T12:44:54.963895+00:00 host app web.1 - Traceback (most recent call last):
14:44:55.282 foundation.mozilla.org logplex <190>1 2019-08-20T12:44:54.963897+00:00 host app web.1 -   File "/app/.heroku/python/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
14:44:55.282 foundation.mozilla.org logplex <190>1 2019-08-20T12:44:54.963898+00:00 host app web.1 -     response = get_response(request)
14:44:55.282 foundation.mozilla.org logplex <190>1 2019-08-20T12:44:54.963900+00:00 host app web.1 -   File "/app/.heroku/python/lib/python3.7/site-packages/django/core/handlers/base.py", line 126, in _get_response
14:44:55.282 foundation.mozilla.org logplex <190>1 2019-08-20T12:44:54.963902+00:00 host app web.1 -     "returned None instead." % (callback.__module__, view_name)
14:44:55.282 foundation.mozilla.org logplex <190>1 2019-08-20T12:44:54.963904+00:00 host app web.1 - ValueError: The view networkapi.views.review_app_help_view didn't return an HttpResponse object. It returned None instead.
```

**Comment by Pomax** [comment]
Looking at the file in question, the code is:
```
def review_app_help_view(request):
    try:
        if settings.HEROKU_APP_NAME:
            return render(request, 'reviewapp-help.html')
    except AttributeError:
        raise Http404()
```
so it's possible the the `try` fails, but not on an `AttributeError`.

**Comment by Pomax** [comment]
looks like we fixed this somewhere along the way - it now returns a 404 instead of crashing on a 500
