### ISSUE TITLE
Can't run load_fake_data twice or delete previous fake data

### ISSUE THREAD

**Issue by patjouk** [mozilla/foundation.mozilla.org#4062]
When I try to run `inv (docker-)manage load_fake_data`, I get this error:

```python
Generating a blog namespace
Traceback (most recent call last):
  File "/app/network-api/networkapi/wagtailpages/factory/blog.py", line 57, in generate
    blog_namespace = WagtailPage.objects.get(title='blog')
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.7/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.7/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
wagtail.core.models.DoesNotExist: Page matching query does not exist.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "network-api/manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.7/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.7/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.7/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.7/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/app/network-api/networkapi/management/commands/load_fake_data.py", line 77, in handle
    mozfest_factory
  File "/app/network-api/networkapi/management/commands/load_fake_data.py", line 70, in <listcomp>
    [app_factory.generate(seed) for app_factory in [
  File "/app/network-api/networkapi/wagtailpages/factory/__init__.py", line 20, in generate
    blog.generate(seed)
  File "/app/network-api/networkapi/wagtailpages/factory/blog.py", line 65, in generate
    live=True
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.7/site-packages/factory/base.py", line 564, in create
    return cls._generate(enums.CREATE_STRATEGY, kwargs)
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.7/site-packages/factory/django.py", line 141, in _generate
    return super(DjangoModelFactory, cls)._generate(strategy, params)
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.7/site-packages/factory/base.py", line 501, in _generate
    return step.build()
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.7/site-packages/factory/builder.py", line 279, in build
    kwargs=kwargs,
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.7/site-packages/factory/base.py", line 315, in instantiate
    return self.factory._create(model, *args, **kwargs)
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.7/site-packages/wagtail_factories/factories.py", line 58, in _create
    instance = cls._create_instance(model_class, parent, kwargs)
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.7/site-packages/wagtail_factories/factories.py", line 66, in _create_instance
    parent.add_child(instance=instance)
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.7/site-packages/treebeard/mp_tree.py", line 1013, in add_child
    return MP_AddChildHandler(self, **kwargs).process()
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.7/site-packages/treebeard/mp_tree.py", line 389, in process
    newobj.save()
  File "/usr/local/lib/python3.7/contextlib.py", line 74, in inner
    return func(*args, **kwds)
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.7/site-packages/wagtail_modeltranslation/patch_wagtailadmin.py", line 507, in __call__
    return self.func(instance, *args, **kwargs)
  File "/usr/local/lib/python3.7/contextlib.py", line 74, in inner
    return func(*args, **kwds)
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.7/site-packages/wagtail/core/models.py", line 442, in save
    self.full_clean()
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.7/site-packages/wagtail/core/models.py", line 432, in full_clean
    super().full_clean(*args, **kwargs)
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.7/site-packages/django/db/models/base.py", line 1203, in full_clean
    raise ValidationError(errors)
django.core.exceptions.ValidationError: {'slug_en': ['This slug is already in use'], 'slug_de': ['This slug is already in use'], 'slug_pt': ['This slug is already in use'], 'slug_es': ['This slug is already in use'], 'slug_fr': ['This slug is already in use'], 'slug_pl': ['This slug is already in use']}
```

Same validation issue when running `inv (docker-)manage "load_fake_data --delete"`.
Current workaround is to create a new DB and run load_fake_data once only.
Might be related to #4024

**Comment by cadecairos** [comment]
This has been resolved
