### ISSUE TITLE
TypeError: this.props.handleCountryChange is not a function

### ISSUE THREAD

**Issue by cadecairos** [mozilla/foundation.mozilla.org#4070]
https://sentry.prod.mozaws.net/operations/foundation-mozilla-org/issues/6864317/

```
TypeError: this.props.handleCountryChange is not a function
  at value (/_js/main.compiled.js:50:70001)
  at onChange (/_js/main.compiled.js:50:70413)
  at h (/_js/main.compiled.js:42:1024)
  at b (/_js/main.compiled.js:42:1167)
  at Y/< (/_js/main.compiled.js:42:1313)
...
(10 additional frame(s) were not displayed)
```

**Comment by cadecairos** [comment]
Sentry issue: [FOUNDATION-MOZILLA-ORG-Z](https://sentry.prod.mozaws.net/operations/foundation-mozilla-org/issues/6864775/)

**Comment by cadecairos** [comment]
Sentry issue: [FOUNDATION-MOZILLA-ORG-19](https://sentry.prod.mozaws.net/operations/foundation-mozilla-org/issues/6875329/)
