### ISSUE TITLE
`inv new-db` crashes

### ISSUE THREAD

**Issue by Pomax** [mozilla/foundation.mozilla.org#5671]
`inv new-db` crashes when it tries to run `participate_page.save()`

```
Traceback (most recent call last):
  File "network-api/manage.py", line 34, in <module>
    execute_from_command_line(sys.argv)
  File "/app/dockerpythonvenv/lib/python3.7/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/app/dockerpythonvenv/lib/python3.7/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/app/dockerpythonvenv/lib/python3.7/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/app/dockerpythonvenv/lib/python3.7/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/app/network-api/networkapi/management/commands/load_fake_data.py", line 76, in handle
    mozfest_factory
  File "/app/network-api/networkapi/management/commands/load_fake_data.py", line 69, in <listcomp>
    [app_factory.generate(seed) for app_factory in [
  File "/app/network-api/networkapi/wagtailpages/factory/__init__.py", line 36, in generate
    publication.generate(seed)
  File "/app/network-api/networkapi/wagtailpages/factory/publication.py", line 110, in generate
    parent=home_page, title='Publication Page with child Article Pages'
  File "/app/dockerpythonvenv/lib/python3.7/site-packages/factory/base.py", line 564, in create
    return cls._generate(enums.CREATE_STRATEGY, kwargs)
  File "/app/dockerpythonvenv/lib/python3.7/site-packages/factory/django.py", line 141, in _generate
    return super(DjangoModelFactory, cls)._generate(strategy, params)
  File "/app/dockerpythonvenv/lib/python3.7/site-packages/factory/base.py", line 501, in _generate
    return step.build()
  File "/app/dockerpythonvenv/lib/python3.7/site-packages/factory/builder.py", line 279, in build
    kwargs=kwargs,
  File "/app/dockerpythonvenv/lib/python3.7/site-packages/factory/base.py", line 315, in instantiate
    return self.factory._create(model, *args, **kwargs)
  File "/app/dockerpythonvenv/lib/python3.7/site-packages/wagtail_factories/factories.py", line 69, in _create
    instance = cls._create_instance(model_class, parent, kwargs)
  File "/app/dockerpythonvenv/lib/python3.7/site-packages/wagtail_factories/factories.py", line 77, in _create_instance
    parent.add_child(instance=instance)
  File "/app/dockerpythonvenv/lib/python3.7/site-packages/treebeard/mp_tree.py", line 1022, in add_child
    return MP_AddChildHandler(self, **kwargs).process()
  File "/app/dockerpythonvenv/lib/python3.7/site-packages/treebeard/mp_tree.py", line 389, in process
    newobj.save()
  File "/usr/local/lib/python3.7/contextlib.py", line 74, in inner
    return func(*args, **kwds)
  File "/app/dockerpythonvenv/lib/python3.7/site-packages/wagtail_modeltranslation/patch_wagtailadmin.py", line 510, in __call__
    return self.func(instance, *args, **kwargs)
  File "/usr/local/lib/python3.7/contextlib.py", line 74, in inner
    return func(*args, **kwds)
  File "/app/dockerpythonvenv/lib/python3.7/site-packages/wagtail/core/models.py", line 630, in save
    self.full_clean()
  File "/app/dockerpythonvenv/lib/python3.7/site-packages/wagtail/core/models.py", line 604, in full_clean
    super().full_clean(*args, **kwargs)
  File "/app/dockerpythonvenv/lib/python3.7/site-packages/django/db/models/base.py", line 1206, in full_clean
    raise ValidationError(errors)
django.core.exceptions.ValidationError: {'slug_en': ['This slug is already in use'], 'slug_de': ['This slug is already in use'], 'slug_pt': ['This slug is already in use'], 'slug_es': ['This slug is already in use'], 'slug_fr': ['This slug is already in use'], 'slug_fy_NL': ['This slug is already in use'], 'slug_nl': ['This slug is already in use'], 'slug_pl': ['This slug is already in use']}
```

**Comment by mmmavis** [comment]
`inv new-env` followed by `inv new-db` works for me without errors.

Note that I didn’t get a chance to try `inv new-db` without running `inv new-env` first because I read your message wrong and thought you were having issues with `inv new-env` 🙈

**Comment by Pomax** [comment]
I think something went very wrong when I was trying to fix some factory code... invalidating for now.
