### ISSUE TITLE
wagtail-localize: set up latest release of wagtail-localize

### ISSUE THREAD

**Issue by TheoChevalier** [mozilla/foundation.mozilla.org#5999]
There’s an initial draft here https://github.com/TheoChevalier/foundation.mozilla.org/commits/wagtail-2-11

### precursory work

- [x] update wagtail-modeltranslation to 0.10.17 in master
- [x] update wagtail  in master to 2.11.3

### dependency work

- [ ] capture all localized page data
- [x] Unhook wagtail (https://github.com/mozilla/foundation.mozilla.org/pull/6085)
  - [x] Delete l10n commands from tasks.py (https://github.com/mozilla/foundation.mozilla.org/pull/6085)
- [x] Install wagtail-localize (https://github.com/mozilla/foundation.mozilla.org/pull/6111)
- [ ] Add the pontoon-connection for wagtail-localize (https://github.com/mozilla/foundation.mozilla.org/pull/6121 pending)
- [ ] ensure redirect tests work; some oddities were discovered, see #6114 

### configuration work

- [ ] cofigure/provision Redis
- [ ] Set custom Django REST API permissions for wagtail-localize https://www.django-rest-framework.org/api-guide/permissions/#custom-permissions
- [ ] Set up wagtail-localize for committing to a GitHub repo via a custom sync manager in `network-api/networkapi/pontoon.py`

**Comment by Pomax** [comment]
Running through https://www.wagtail-localize.org/how-to/integrations/pontoon/
- created test user https://github.com/jurrich
- created test repo https://github.com/Pomax/test-repo-for-wagtail-localization
- created heroku app https://dashboard.heroku.com/apps/wagtail-localize-staging
- it is unclear how the Deploy Keys and SSH keys are meant to work: SSH keys are added to user accounts, not to repos, but the docs don't mention creating a dedicated wagtail-localize user. Repos have deploy keys, but the docs don't mention how to use _those_ instead of SSH keys
- variables for Heroku set as:
  - `WAGTAILLOCALIZE_GIT_CLONE_DIR=/tmp/wagtail-content-for-pontoon.git`
  - `WAGTAILLOCALIZE_GIT_URL=git@github.com:Pomax/test-repo-for-wagtail-localization.git`
  - `TARGET_DOMAINS=wagtail-localize-staging.herokuapp.com`
  - `SSH_PRIVATE_KEY=......base64 encoded private SSH key...`

Unforunately this leads to:

```
INFO - Pulling repository
Checked out an empty repository
INFO - Pull: No changes since last sync
INFO - Push: Committing changes
Traceback (most recent call last):
  File "network-api/manage.py", line 34, in <module>
    execute_from_command_line(sys.argv)
  File "/app/.heroku/python/lib/python3.7/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/app/.heroku/python/lib/python3.7/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/app/.heroku/python/lib/python3.7/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/app/.heroku/python/lib/python3.7/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/app/.heroku/python/lib/python3.7/site-packages/wagtail_localize_git/management/commands/sync_git.py", line 19, in handle
    SyncManager(logger=logger).sync()
  File "/app/.heroku/python/lib/python3.7/site-packages/wagtail_localize_git/sync.py", line 166, in sync
    _push(repo, self.logger)
  File "/app/.heroku/python/lib/python3.7/contextlib.py", line 74, in inner
    return func(*args, **kwds)
  File "/app/.heroku/python/lib/python3.7/site-packages/wagtail_localize_git/sync.py", line 136, in _push
    log.commit_id = writer.commit("Updates to source content")
  File "/app/.heroku/python/lib/python3.7/site-packages/wagtail_localize_git/git.py", line 162, in commit
    "HEAD", sig, sig, message, tree, []
_pygit2.GitError: failed to create commit: current tip is not the first parent
Process exited with status 1
```

**Comment by kaedroho** [comment]
Hmm, maybe it's having difficulty because it's an empty repository? Could you try committing something like a readme to the repo and run the sync again?

**Comment by Pomax** [comment]
Hmm, there is a readme, though.

**Comment by Pomax** [comment]
I think I did the shh key bindings wrong, rerunning the instructions, hopefully that fixes it =)

**Comment by Pomax** [comment]
Hm, so there's no git error now, but the app still yields 400 errors... log:
```
2021-04-08T17:01:33.494322+00:00 heroku[web.1]: Stopping all processes with SIGTERM
2021-04-08T17:01:35.597535+00:00 heroku[web.1]: Process exited with status 0
2021-04-08T17:01:53.559019+00:00 heroku[web.1]: Starting process with command `cd network-api && gunicorn networkapi.wsgi:application --preload --max-requests 2000`
2021-04-08T17:01:56.582767+00:00 app[web.1]: Generating SSH config
2021-04-08T17:01:56.604554+00:00 app[web.1]: Done!
2021-04-08T17:01:57.576030+00:00 app[web.1]: /app/.heroku/python/lib/python3.7/site-packages/environ/environ.py:630: UserWarning: /app/network-api/networkapi/.env doesn't exist - if you're not configuring your environment separately, create one.
2021-04-08T17:01:57.576050+00:00 app[web.1]:   "environment separately, create one." % env_file)
2021-04-08T17:02:02.171361+00:00 heroku[web.1]: State changed from starting to up
2021-04-08T17:02:16.190114+00:00 heroku[router]: at=info method=GET path="/" host=wagtail-localize-staging.herokuapp.com request_id=44fe895d-345f-4314-a796-dce8cb4ec7e2 fwd="24.68.32.91" dyno=web.1 connect=1ms service=1179ms status=400 bytes=1786 protocol=https
2021-04-08T17:02:16.315940+00:00 heroku[router]: at=info method=GET path="/favicon.ico" host=wagtail-localize-staging.herokuapp.com request_id=cb237eb2-33f1-4114-860f-3154eea88475 fwd="24.68.32.91" dyno=web.1 connect=1ms service=6ms status=400 bytes=1786 protocol=https
2021-04-08T17:03:00.599624+00:00 heroku[router]: at=info method=GET path="/" host=wagtail-localize-staging.herokuapp.com request_id=4dd9f6ba-7555-4bce-8cef-71c15b694084 fwd="24.68.32.91" dyno=web.1 connect=1ms service=12ms status=400 bytes=1786 protocol=https
2021-04-08T17:03:00.726115+00:00 heroku[router]: at=info method=GET path="/favicon.ico" host=wagtail-localize-staging.herokuapp.com request_id=eae4583b-127c-4382-a9c6-7da50963c974 fwd="24.68.32.91" dyno=web.1 connect=3ms service=21ms status=400 bytes=1786 protocol=https
```

**Comment by Pomax** [comment]
running with DEBUG=True, we're hitting some vars that _need_ to be set, and may need warnings added into the startup:

- TARGET_DOMAIN
- ALLOWED_HOSTS

**Comment by Pomax** [comment]
With the above variables cleared, the app gets up and running, so I created a new locale for Dutch, set it as synced to English, and then translated the wagtail welcome page by clicking "Translate this page", then clicking "translate" for the title field, and clicking "save" once I had a translation done. 

This resulted in a "server error" notice on the page, with the follow log on the backend:
```
request_id=a70be24d-38b6-485c-8432-08f902c8f7e2 fwd="24.68.32.91" dyno=web.1 connect=1ms service=233ms status=500 bytes=7959 protocol=https
2021-04-08T17:15:59.212557+00:00 app[web.1]: Internal Server Error: /cms/localize/translate/1/strings/1/edit/
2021-04-08T17:15:59.212567+00:00 app[web.1]: Traceback (most recent call last):
2021-04-08T17:15:59.212569+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
2021-04-08T17:15:59.212570+00:00 app[web.1]:     response = get_response(request)
2021-04-08T17:15:59.212576+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
2021-04-08T17:15:59.212578+00:00 app[web.1]:     response = self.process_exception_by_middleware(e, request)
2021-04-08T17:15:59.212578+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
2021-04-08T17:15:59.212579+00:00 app[web.1]:     response = wrapped_callback(request, *callback_args, **callback_kwargs)
2021-04-08T17:15:59.212579+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/contextlib.py", line 74, in inner
2021-04-08T17:15:59.212580+00:00 app[web.1]:     return func(*args, **kwds)
2021-04-08T17:15:59.212580+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
2021-04-08T17:15:59.212580+00:00 app[web.1]:     response = view_func(request, *args, **kwargs)
2021-04-08T17:15:59.212581+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/wagtail/admin/urls/__init__.py", line 127, in wrapper
2021-04-08T17:15:59.212581+00:00 app[web.1]:     return view_func(request, *args, **kwargs)
2021-04-08T17:15:59.212582+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/wagtail/admin/auth.py", line 193, in decorated_view
2021-04-08T17:15:59.212582+00:00 app[web.1]:     return view_func(request, *args, **kwargs)
2021-04-08T17:15:59.212583+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
2021-04-08T17:15:59.212583+00:00 app[web.1]:     return view_func(*args, **kwargs)
2021-04-08T17:15:59.212584+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/django/views/generic/base.py", line 71, in view
2021-04-08T17:15:59.212584+00:00 app[web.1]:     return self.dispatch(request, *args, **kwargs)
2021-04-08T17:15:59.212585+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/rest_framework/views.py", line 509, in dispatch
2021-04-08T17:15:59.212585+00:00 app[web.1]:     response = self.handle_exception(exc)
2021-04-08T17:15:59.212586+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/rest_framework/views.py", line 469, in handle_exception
2021-04-08T17:15:59.212586+00:00 app[web.1]:     self.raise_uncaught_exception(exc)
2021-04-08T17:15:59.212586+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
2021-04-08T17:15:59.212587+00:00 app[web.1]:     raise exc
2021-04-08T17:15:59.212588+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/rest_framework/views.py", line 497, in dispatch
2021-04-08T17:15:59.212588+00:00 app[web.1]:     self.initial(request, *args, **kwargs)
2021-04-08T17:15:59.212589+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/rest_framework/views.py", line 415, in initial
2021-04-08T17:15:59.212589+00:00 app[web.1]:     self.check_permissions(request)
2021-04-08T17:15:59.212589+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/rest_framework/views.py", line 332, in check_permissions
2021-04-08T17:15:59.212590+00:00 app[web.1]:     if not permission.has_permission(request, self):
2021-04-08T17:15:59.212590+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/rest_framework/permissions.py", line 229, in has_permission
2021-04-08T17:15:59.212591+00:00 app[web.1]:     queryset = self._queryset(view)
2021-04-08T17:15:59.212591+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/rest_framework/permissions.py", line 209, in _queryset
2021-04-08T17:15:59.212591+00:00 app[web.1]:     ).format(self.__class__.__name__)
2021-04-08T17:15:59.212593+00:00 app[web.1]: AssertionError: Cannot apply DjangoModelPermissionsOrAnonReadOnly on a view that does not set `.queryset` or have a `.get_queryset()` method.
```

**Comment by Pomax** [comment]
Also seeing  `_pygit2.GitError: failed to create commit: current tip is not the first parent` happen after a while now, but I'm not sure if that's now because of the above error...
