### ISSUE TITLE
🔥 server error 500 caused by  wagtailinventory

### ISSUE THREAD

**Issue by Pomax** [mozilla/foundation.mozilla.org#6162]
### Describe the bug

```
2021-02-04T17:55:17.882093+00:00 heroku[router]: at=info method=POST path="/cms/pages/1313/edit/" host=foundation.mozilla.org request_id=6839fa92-6ad2-4a4c-bd15-03ece398d22b fwd="45.48.232.173" dyno=web.1 connect=0ms service=3238ms status=500 bytes=2297 protocol=https
2021-02-04T17:55:17.872112+00:00 app[web.1]: Internal Server Error: /cms/pages/1313/edit/
2021-02-04T17:55:17.872125+00:00 app[web.1]: Traceback (most recent call last):
2021-02-04T17:55:17.872126+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
2021-02-04T17:55:17.872127+00:00 app[web.1]:     response = get_response(request)
2021-02-04T17:55:17.872128+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
2021-02-04T17:55:17.872129+00:00 app[web.1]:     response = self.process_exception_by_middleware(e, request)
2021-02-04T17:55:17.872130+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
2021-02-04T17:55:17.872131+00:00 app[web.1]:     response = wrapped_callback(request, *callback_args, **callback_kwargs)
2021-02-04T17:55:17.872132+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/sentry_sdk/integrations/django/views.py", line 67, in sentry_wrapped_callback
2021-02-04T17:55:17.872132+00:00 app[web.1]:     return callback(request, *args, **kwargs)
2021-02-04T17:55:17.872133+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/contextlib.py", line 74, in inner
2021-02-04T17:55:17.872134+00:00 app[web.1]:     return func(*args, **kwds)
2021-02-04T17:55:17.872134+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
2021-02-04T17:55:17.872135+00:00 app[web.1]:     response = view_func(request, *args, **kwargs)
2021-02-04T17:55:17.872135+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/wagtail/admin/urls/__init__.py", line 127, in wrapper
2021-02-04T17:55:17.872136+00:00 app[web.1]:     return view_func(request, *args, **kwargs)
2021-02-04T17:55:17.872136+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/wagtail/admin/auth.py", line 172, in decorated_view
2021-02-04T17:55:17.872137+00:00 app[web.1]:     response = view_func(request, *args, **kwargs)
2021-02-04T17:55:17.872137+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/django/views/generic/base.py", line 71, in view
2021-02-04T17:55:17.872138+00:00 app[web.1]:     return self.dispatch(request, *args, **kwargs)
2021-02-04T17:55:17.872138+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/wagtail/admin/views/pages/edit.py", line 131, in dispatch
2021-02-04T17:55:17.872139+00:00 app[web.1]:     return super().dispatch(request)
2021-02-04T17:55:17.872139+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/django/views/generic/base.py", line 97, in dispatch
2021-02-04T17:55:17.872140+00:00 app[web.1]:     return handler(request, *args, **kwargs)
2021-02-04T17:55:17.872140+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/wagtail/admin/views/pages/edit.py", line 218, in post
2021-02-04T17:55:17.872145+00:00 app[web.1]:     return self.form_valid(self.form)
2021-02-04T17:55:17.872145+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/wagtail/admin/views/pages/edit.py", line 238, in form_valid
2021-02-04T17:55:17.872146+00:00 app[web.1]:     return self.publish_action()
2021-02-04T17:55:17.872146+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/wagtail/admin/views/pages/edit.py", line 351, in publish_action
2021-02-04T17:55:17.872147+00:00 app[web.1]:     response = self.run_hook('after_edit_page', self.request, self.page)
2021-02-04T17:55:17.872148+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/wagtail/admin/views/generic.py", line 60, in run_hook
2021-02-04T17:55:17.872148+00:00 app[web.1]:     result = fn(*args, **kwargs)
2021-02-04T17:55:17.872148+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/wagtailinventory/wagtail_hooks.py", line 31, in do_after_page_edit
2021-02-04T17:55:17.872149+00:00 app[web.1]:     update_page_inventory(page)
2021-02-04T17:55:17.872149+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/wagtailinventory/helpers.py", line 70, in update_page_inventory
2021-02-04T17:55:17.872150+00:00 app[web.1]:     page_blocks = create_page_inventory(page)
2021-02-04T17:55:17.872150+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/wagtailinventory/helpers.py", line 61, in create_page_inventory
2021-02-04T17:55:17.872151+00:00 app[web.1]:     for block in page_blocks
2021-02-04T17:55:17.872151+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/wagtailinventory/helpers.py", line 61, in <listcomp>
2021-02-04T17:55:17.872152+00:00 app[web.1]:     for block in page_blocks
2021-02-04T17:55:17.872152+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/django/db/models/manager.py", line 82, in manager_method
2021-02-04T17:55:17.872152+00:00 app[web.1]:     return getattr(self.get_queryset(), name)(*args, **kwargs)
2021-02-04T17:55:17.872153+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/django/db/models/query.py", line 538, in get_or_create
2021-02-04T17:55:17.872153+00:00 app[web.1]:     return self.get(**kwargs), False
2021-02-04T17:55:17.872154+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/django/db/models/query.py", line 412, in get
2021-02-04T17:55:17.872154+00:00 app[web.1]:     (self.model._meta.object_name, num)
2021-02-04T17:55:17.872155+00:00 app[web.1]: wagtailinventory.models.PageBlock.MultipleObjectsReturned: get() returned more than one PageBlock -- it returned 2!
```

### To Reproduce

1. Set up a copy of the live data
1. Go to http://localhost:8000/cms/pages/1313/edit/
1. Try to update the SEO image in the `promote` tab
1. You'll get a server error 500 with the above stack trace in the console

### Additional details

![image](https://user-images.githubusercontent.com/177243/106941545-d6a3e880-66d7-11eb-979f-be0c45e5c86f.png)

**Comment by Pomax** [comment]
It looks like we're already on the latest version of wagtail-inventory so the immediate solution is going to be "remove wagtail-inventory", with a test that replicates the actions that cause the error. We can then schedule a reintroduction of wagtail-inventory.

(I don't know if we're still getting much use out of it now that we're mostly maintaining, rather than developing new blocks with a need to update block types on pages)

**Comment by Pomax** [comment]
Rather than removing `wagtail-inventory`, we could do a fork of the project, fix the one file to use this code instead:
```python

def create_page_inventory(page):
    page_blocks = get_page_blocks(page)

    # return [
    #     PageBlock.objects.get_or_create(page=page, block=block)[0]
    #     for block in page_blocks
    # ]

    list = []
    for block in page_blocks:
        bindings = PageBlock.objects.filter(page=page, block=block)

        if bindings.count() > 0:
            list.append(bindings.first())
            for index, entry in enumerate(bindings):
                if index > 0:
                    entry.delete()
        else:
            (result, created) = PageBlock.objects.get_or_create(page=page, block=block)
            list.append(result)

    return list
```
and then point to that update as dependency instead. This will both clean up the duplication and "not crash things" while we try to figure out what the long term solution would be here.

**Comment by Pomax** [comment]
I've created https://github.com/Pomax/wagtail-inventory/commit/ea9a6533e69ff0a6faaf0f069efa115bc22ce697 for the updated `helper.py`

**Comment by Pomax** [comment]
I've also filed https://github.com/cfpb/wagtail-inventory/issues/43 to see if this is something that's worth detecting in wagtail-inventory itself, or whether we're going to have to figure out a cleaner way to carry over this patch without breaking dependency management.

(Not a fan of github commits, they tend to disappear after some time. Even if they're mine =D)

**Comment by Pomax** [comment]
Initial PR landed so that staff will at least not run into server error 500 anymore, but it's more a hotfix than anything and we still need to properly solve this problem (I don't think we can rigorously prevent this from happening again, this feels like the kind of race condition row duplication that you get from having multiple dynos running...)

**Comment by benhohner** [comment]
Looks good. Can we create a follow-up ticket now so we don't forget to off our fork when we figure out a permanent solution?

**Comment by Pomax** [comment]
filed #6184 as follow-up
