### ISSUE TITLE
index page Queryset iteration can fail

### ISSUE THREAD

**Issue by Pomax** [mozilla/foundation.mozilla.org#6255]
### Describe the bug

```
Feb 23 19:35:38 foundation-mozilla-org app/web.3 Internal Server Error: /en/blog/category/mozilla-festival/
Feb 23 19:35:38 foundation-mozilla-org app/web.3 Traceback (most recent call last):
Feb 23 19:35:38 foundation-mozilla-org app/web.3   File "/app/.heroku/python/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
Feb 23 19:35:38 foundation-mozilla-org app/web.3     response = get_response(request)
Feb 23 19:35:38 foundation-mozilla-org app/web.3   File "/app/.heroku/python/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
Feb 23 19:35:38 foundation-mozilla-org app/web.3     response = self.process_exception_by_middleware(e, request)
Feb 23 19:35:38 foundation-mozilla-org app/web.3   File "/app/.heroku/python/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
Feb 23 19:35:38 foundation-mozilla-org app/web.3     response = wrapped_callback(request, *callback_args, **callback_kwargs)
Feb 23 19:35:38 foundation-mozilla-org app/web.3   File "/app/.heroku/python/lib/python3.7/site-packages/sentry_sdk/integrations/django/views.py", line 67, in sentry_wrapped_callback
Feb 23 19:35:38 foundation-mozilla-org app/web.3     return callback(request, *args, **kwargs)
Feb 23 19:35:38 foundation-mozilla-org app/web.3   File "/app/.heroku/python/lib/python3.7/contextlib.py", line 74, in inner
Feb 23 19:35:38 foundation-mozilla-org app/web.3     return func(*args, **kwds)
Feb 23 19:35:38 foundation-mozilla-org app/web.3   File "/app/.heroku/python/lib/python3.7/site-packages/wagtail/core/views.py", line 24, in serve
Feb 23 19:35:38 foundation-mozilla-org app/web.3     return page.serve(request, *args, **kwargs)
Feb 23 19:35:38 foundation-mozilla-org app/web.3   File "/app/.heroku/python/lib/python3.7/site-packages/wagtail/contrib/routable_page/models.py", line 121, in serve
Feb 23 19:35:38 foundation-mozilla-org app/web.3     return view(request, *args, **kwargs)
Feb 23 19:35:38 foundation-mozilla-org app/web.3   File "/app/network-api/networkapi/wagtailpages/pagemodels/blog/blog_index.py", line 159, in entries_by_category
Feb 23 19:35:38 foundation-mozilla-org app/web.3     return IndexPage.serve(self, request, *args, **kwargs)
Feb 23 19:35:38 foundation-mozilla-org app/web.3   File "/app/.heroku/python/lib/python3.7/site-packages/wagtail/contrib/routable_page/models.py", line 120, in serve
Feb 23 19:35:38 foundation-mozilla-org app/web.3     return super().serve(request, *args, **kwargs)
Feb 23 19:35:38 foundation-mozilla-org app/web.3   File "/app/.heroku/python/lib/python3.7/site-packages/wagtail/core/models.py", line 1553, in serve
Feb 23 19:35:38 foundation-mozilla-org app/web.3     self.get_context(request, *args, **kwargs)
Feb 23 19:35:38 foundation-mozilla-org app/web.3   File "/app/network-api/networkapi/wagtailpages/pagemodels/index.py", line 69, in get_context
Feb 23 19:35:38 foundation-mozilla-org app/web.3     entries = self.get_entries(context)
Feb 23 19:35:38 foundation-mozilla-org app/web.3   File "/app/network-api/networkapi/wagtailpages/pagemodels/index.py", line 87, in get_entries
Feb 23 19:35:38 foundation-mozilla-org app/web.3     entries = self.filter_entries(entries, context)
Feb 23 19:35:38 foundation-mozilla-org app/web.3   File "/app/network-api/networkapi/wagtailpages/pagemodels/blog/blog_index.py", line 76, in filter_entries
Feb 23 19:35:38 foundation-mozilla-org app/web.3     entries = self.filter_entries_for_category(entries, context)
Feb 23 19:35:38 foundation-mozilla-org app/web.3   File "/app/network-api/networkapi/wagtailpages/pagemodels/blog/blog_index.py", line 99, in filter_entries_for_category
Feb 23 19:35:38 foundation-mozilla-org app/web.3     entry in entries.specific()
Feb 23 19:35:38 foundation-mozilla-org app/web.3   File "/app/network-api/networkapi/wagtailpages/pagemodels/blog/blog_index.py", line 103, in <listcomp>
Feb 23 19:35:38 foundation-mozilla-org app/web.3     category in entry.category.all()
Feb 23 19:35:38 foundation-mozilla-org app/web.3 TypeError: argument of type 'QuerySet' is not iterable
```

### To Reproduce

Literally no idea: it happens every so often, but when I check the associated URL, it works fine. Searching the web reveals that this isn't actually the QuerySet not being iterable, but the iterator throwing an error internally, which is caught by Django as a "QuerySet is not iterable" error.

See https://code.djangoproject.com/ticket/26600

### Expected behavior

No errors. This should jsut work

### Solutions

We should at the very least wrap the code involved with a try/except so that we can manage the response. Presumably folks are getting a "Server error 500" instead of normal-ish page, which should be avoided.

**Comment by Pomax** [comment]
Immediate steps:
- [ ] rewrite the list comprehension to a for loop with try/except checks around the "x in y" statements.
- [ ] forward those exceptions to Sentry, if sentry's active

**Comment by Pomax** [comment]
After these steps, I will move this issue into the backlog until there's new evidence we can act on =(

**Comment by KalobTaulien** [comment]
@Pomax Moving this to icebox until there's more evidence to work off of. Just wanted to keep you informed.

**Comment by jamilasnell** [comment]
We haven't seen anything come up lately so we are closing this. Feel free to re-open if same issue persists.

**Comment by tbrlpld** [comment]
I am running into issue with this code now, because it converts from a QuerySet to a list. Why were we iterating in Python in the first place? It seems like this kind of filtering would be best done on the database level. 

See also: https://stackoverflow.com/questions/4507893/django-filter-many-to-many-with-contains

**Comment by Pomax** [comment]
If memory serves correct, it's because it used to have to filter several non-unifiable page types (way back when).

**Comment by mtdenton** [comment]
@cdanfon here's a good candidate for upcoming maintenance

**Comment by tbrlpld** [comment]
I cannot find any Sentry logs (on the new and old instance) for these issues. I guess we can remove the logging code. If the issue pops back  up, we should address it then with more information.

**Comment by tbrlpld** [comment]
We can also simplify the original code, since we only allow `BlogPage` as subpages of `BlogIndexPage` now.

**Comment by tbrlpld** [comment]
@cdanfon Not super sure what's best to test this. This is a technical change with like-for-like functionality. I  guess we can only make sure that the blog index still works: https://foundation.mofostaging.net/en/blog/

**Comment by cdanfon** [comment]
@tbrlpld I've checked the blog index in https://foundation.mofostaging.net/en/blog/ and looks good to me, marking this as passed

**Comment by tbrlpld** [comment]
This is already in production.
