### ISSUE TITLE
"npm test" task throws error (Cannot find module 'esbuild') 

### ISSUE THREAD

**Issue by mmmavis** [mozilla/foundation.mozilla.org#6432]
Running `npm test` gives me

```bash
...
...
...
> @ build:common /Users/mavis/Development/foundation.mozilla.org
> run-p build:images build:sass build:contribute

> @ build:js:prod /Users/mavis/Development/foundation.mozilla.org
> node esbuild.config.js -- --node-env production

internal/modules/cjs/loader.js:613
    throw err;
    ^

Error: Cannot find module 'esbuild'
Require stack:
- /Users/mavisou/Development/foundation.mozilla.org/esbuild.config.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:610:15)
    at Function.Module._load (internal/modules/cjs/loader.js:526:27)
    at Module.require (internal/modules/cjs/loader.js:666:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (/Users/mavisou/Development/foundation.mozilla.org/esbuild.config.js:11:19)
    at Module._compile (internal/modules/cjs/loader.js:759:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:770:10)
    at Module.load (internal/modules/cjs/loader.js:628:32)
    at Function.Module._load (internal/modules/cjs/loader.js:555:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:826:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ build:js:prod: `node esbuild.config.js -- --node-env production`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ build:js:prod script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/mavisou/.npm/_logs/2021-03-24T23_34_57_268Z-debug.log
ERROR: "build:js:prod" exited with 1.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ build: `run-s build:clean && run-p build:js:prod build:common`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/mavisou/.npm/_logs/2021-03-24T23_34_57_401Z-debug.log
ERROR: "build" exited with 1.
npm ERR! Test failed.  See above for more details.
```

**Comment by mmmavis** [comment]
False alarm. I just need to run it inside docker. i.e., `inv npm "test"`
