### ISSUE TITLE
[wagtail-localize] Support Recent blog entries blocks

### ISSUE THREAD

**Issue by TheoChevalier** [mozilla/foundation.mozilla.org#7153]
https://foundation-localize.herokuapp.com/de/campaigns/election-integrity-and-platform-accountability/ is crashing, looks like we will need to filter objects in "Recent blog entries" blocks

`networkapi.wagtailpages.pagemodels.blog.blog_index.BlogIndexPage.MultipleObjectsReturned: get() returned more than one BlogIndexPage -- it returned 8!`

```
2021-07-30T14:52:20.881072+00:00 app[web.1]: 

2021-07-30T14:52:20.881087+00:00 app[web.1]: ----intercepted 500 error stack trace----

2021-07-30T14:52:20.881088+00:00 app[web.1]: get() returned more than one BlogIndexPage -- it returned 8!

2021-07-30T14:52:20.881089+00:00 app[web.1]: <class 'networkapi.wagtailpages.pagemodels.blog.blog_index.BlogIndexPage.MultipleObjectsReturned'>

2021-07-30T14:52:20.886917+00:00 app[web.1]: ['Traceback (most recent call last):\n', '  File "/app/.heroku/python/lib/python3.7/site-packages/django/core/handlers/exception.py", line 47, in inner\n    response = get_response(request)\n', '  File "/app/.heroku/python/lib/python3.7/site-packages/django/core/handlers/base.py", line 204, in _get_response\n    response = response.render()\n', '  File "/app/.heroku/python/lib/python3.7/site-packages/django/template/response.py", line 105, in render\n    self.content = self.rendered_content\n', '  File "/app/.heroku/python/lib/python3.7/site-packages/django/template/response.py", line 83, in rendered_content\n    return template.render(context, self._request)\n', '  File "/app/.heroku/python/lib/python3.7/site-packages/django/template/backends/django.py", line 61, in render\n    return self.template.render(context)\n', '  File "/app/.heroku/python/lib/python3.7/site-packages/django/template/base.py", line 170, in render\n    return self._render(context)\n', '  File "/app/.heroku/python/lib/python3.7/site-packages/django/template/base.py", line 162, in _render\n    return self.nodelist.render(context)\n', '  File "/app/.heroku/python/lib/python3.7/site-packages/django/template/base.py", line 938, in render\n    bit = node.render_annotated(context)\n', '  File "/app/.heroku/python/lib/python3.7/site-packages/django/template/base.py", line 905, in render_annotated\n    return self.render(context)\n', '  File "/app/.heroku/python/lib/python3.7/site-packages/django/template/loader_tags.py", line 150, in render\n    return compiled_parent._render(context)\n', '  File "/app/.heroku/python/lib/python3.7/site-packages/django/template/base.py", line 162, in _render\n    return self.nodelist.render(context)\n', '  File "/app/.heroku/python/lib/python3.7/site-packages/django/template/base.py", line 938, in render\n    bit = node.render_annotated(context)\n', '  File "/app/.heroku/python/lib/python3.7/site-packages/django/template/base.py", line 905, in render_annotated\n    return self.render(context)\n', '  File "/app/.heroku/python/lib/python3.7/site-packages/django/template/loader_tags.py", line 150, in render\n    return compiled_parent._render(context)\n', '  File "/app/.heroku/python/lib/python3.7/site-packages/django/template/base.py", line 162, in _render\n    return self.nodelist.render(context)\n', '  File "/app/.heroku/python/lib/python3.7/site-packages/django/template/base.py", line 938, in render\n    bit = node.render_annotated(context)\n', '  File "/app/.heroku/python/lib/python3.7/site-packages/django/template/base.py", line 905, in render_annotated\n    return self.render(context)\n', '  File "/app/.heroku/python/lib/python3.7/site-packages/django/template/loader_tags.py", line 150, in render\n    return compiled_parent._render(context)\n', '  File "/app/.heroku/python/lib/python3.7/site-packages/django/template/base.py", line 162, in _render\n    return self.nodelist.render(context)\n', '  File "/app/.heroku/python/lib/python3.7/site-packages/django/template/base.py", line 938, in render\n    bit = node.render_annotated(context)\n', '  File "/app/.heroku/python/lib/python3.7/site-packages/django/template/base.py", line 905, in render_annotated\n    return self.render(context)\n', '  File "/app/.heroku/python/lib/python3.7/site-packages/django/template/loader_tags.py", line 150, in render\n    return compiled_parent._render(context)\n', '  File "/app/.heroku/python/lib/python3.7/site-packages/django/template/base.py", line 162, in _render\n    return self.nodelist.render(context)\n', '  File "/app/.heroku/python/lib/python3.7/site-packages/django/template/base.py", line 938, in render\n    bit = node.render_annotated(context)\n', '  File "/app/.heroku/python/lib/python3.7/site-packages/django/template/base.py", line 905, in render_annotated\n    return self.render(context)\n', '  File "/app/.heroku/python/lib/python3.7/site-packages/django/template/loader_tags.py", line 62, in render\n    result = block.nodelist.render(context)\n', '  File "/app/.heroku/python/lib/python3.7/site-packages/django/template/base.py", line 938, in render\n    bit = node.render_annotated(context)\n', '  File "/app/.heroku/python/lib/python3.7/site-packages/django/template/base.py", line 905, in render_annotated\n    return self.render(context)\n', '  File "/app/.heroku/python/lib/python3.7/site-packages/django/template/loader_tags.py", line 62, in render\n    result = block.nodelist.render(context)\n', '  File "/app/.heroku/python/lib/python3.7/site-packages/django/template/base.py", line 938, in render\n    bit = node.render_annotated(context)\n', '  File "/app/.heroku/python/lib/python3.7/site-packages/django/template/base.py", line 905, in render_annotated\n    return self.render(context)\n', '  File "/app/.heroku/python/lib/python3.7/site-packages/django/template/loader_tags.py", line 62, in render\n    result = block.nodelist.render(context)\n', '  File "/app/.heroku/python/lib/python3.7/site-packages/django/template/base.py", line 938, in render\n    bit = node.render_annotated(context)\n', '  File "/app/.heroku/python/lib/python3.7/site-packages/django/template/base.py", line 905, in render_annotated\n    return self.render(context)\n', '  File "/app/.heroku/python/lib/python3.7/site-packages/django/template/loader_tags.py", line 62, in render\n    result = block.nodelist.render(context)\n', '  File "/app/.heroku/python/lib/python3.7/site-packages/django/template/base.py", line 938, in render\n    bit = node.render_annotated(context)\n', '  File "/app/.heroku/python/lib/python3.7/site-packages/django/template/base.py", line 905, in render_annotated\n    return self.render(context)\n', '  File "/app/.heroku/python/lib/python3.7/site-packages/django/template/loader_tags.py", line 62, in render\n    result = block.nodelist.render(context)\n', '  File "/app/.heroku/python/lib/python3.7/site-packages/django/template/base.py", line 938, in render\n    bit = node.render_annotated(context)\n', '  File "/app/.heroku/python/lib/python3.7/site-packages/django/template/base.py", line 905, in render_annotated\n    return self.render(context)\n', '  File "/app/.heroku/python/lib/python3.7/site-packages/django/template/defaulttags.py", line 211, in render\n    nodelist.append(node.render_annotated(context))\n', '  File "/app/.heroku/python/lib/python3.7/site-packages/django/template/base.py", line 905, in render_annotated\n    return self.render(context)\n', '  File "/app/.heroku/python/lib/python3.7/site-packages/django/template/defaulttags.py", line 312, in render\n    return nodelist.render(context)\n', '  File "/app/.heroku/python/lib/python3.7/site-packages/django/template/base.py", line 938, in render\n    bit = node.render_annotated(context)\n', '  File "/app/.heroku/python/lib/python3.7/site-packages/django/template/base.py", line 905, in render_annotated\n    return self.render(context)\n', '  File "/app/.heroku/python/lib/python3.7/site-packages/wagtail/core/templatetags/wagtailcore_tags.py", line 133, in render\n    return value.render_as_block(context=new_context)\n', '  File "/app/.heroku/python/lib/python3.7/site-packages/wagtail/core/blocks/base.py", line 419, in render_as_block\n    return self.block.render(self.value, context=context)\n', '  File "/app/.heroku/python/lib/python3.7/site-packages/wagtail/core/blocks/base.py", line 219, in render\n    new_context = self.get_context(value, parent_context=dict(context))\n', '  File "/app/network-api/networkapi/wagtailpages/pagemodels/customblocks/recent_blog_entries.py", line 43, in get_context\n    blogpage = BlogIndexPage.objects.get(title__iexact="blog")\n', '  File "/app/.heroku/python/lib/python3.7/site-packages/django/db/models/manager.py", line 85, in manager_method\n    return getattr(self.get_queryset(), name)(*args, **kwargs)\n', '  File "/app/.heroku/python/lib/python3.7/site-packages/django/db/models/query.py", line 436, in get\n    num if not limit or num < limit else \'more than %s\' % (limit - 1),\n', 'networkapi.wagtailpages.pagemodels.blog.blog_index.BlogIndexPage.MultipleObjectsReturned: get() returned more than one BlogIndexPage -- it returned 8!\n']

2021-07-30T14:52:20.886951+00:00 app[web.1]: ----

2021-07-30T14:52:20.886975+00:00 app[web.1]: 

2021-07-30T14:52:20.913262+00:00 heroku[router]: at=info method=GET path="/de/campaigns/election-integrity-and-platform-accountability/" host=foundation-localize.herokuapp.com request_id=7594c3dd-0eb7-410a-b424-881d8e17920d fwd="109.220.173.116" dyno=web.1 connect=0ms service=449ms status=404 bytes=2040 protocol=https
```

**Comment by Pomax** [comment]
superceded
