### ISSUE TITLE
Increase character limit for PNI category names

### ISSUE THREAD

**Issue by TheoChevalier** [mozilla/foundation.mozilla.org#7789]
sync_git is failing with French translations of some PNI product category names. I’d suggest we set that limit to 100 chars to keep a margin.

```
INFO - Pull: Importing changes in file 'locales/fr/snippets/wagtailpages.BuyersGuideProductCategory/117-wearables-smart-glasses-ar-headsets-sort-order-1.po'
Traceback (most recent call last):
  File "/app/.heroku/python/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.StringDataRightTruncation: value too long for type character varying(50)


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "network-api/manage.py", line 34, in <module>
    execute_from_command_line(sys.argv)
  File "/app/.heroku/python/lib/python3.7/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/app/.heroku/python/lib/python3.7/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/app/.heroku/python/lib/python3.7/site-packages/django/core/management/base.py", line 330, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/app/.heroku/python/lib/python3.7/site-packages/django/core/management/base.py", line 371, in execute
    output = self.handle(*args, **options)
  File "/app/.heroku/python/lib/python3.7/site-packages/wagtail_localize_git/management/commands/sync_git.py", line 19, in handle
    SyncManager(logger=logger).sync()
  File "/app/.heroku/python/lib/python3.7/site-packages/wagtail_localize_git/sync.py", line 165, in sync
    _pull(repo, self.logger)
  File "/app/.heroku/python/lib/python3.7/contextlib.py", line 74, in inner
    return func(*args, **kwds)
  File "/app/.heroku/python/lib/python3.7/site-packages/wagtail_localize_git/sync.py", line 39, in _pull
    importer.import_resource(translation, po)
  File "/app/.heroku/python/lib/python3.7/contextlib.py", line 74, in inner
    return func(*args, **kwds)
  File "/app/.heroku/python/lib/python3.7/site-packages/wagtail_localize_git/importer.py", line 29, in import_resource
    translation.save_target()
  File "/app/.heroku/python/lib/python3.7/site-packages/wagtail_localize/models.py", line 1241, in save_target
    copy_parent_pages=True,
  File "/app/.heroku/python/lib/python3.7/site-packages/wagtail_localize/models.py", line 782, in create_or_update_translation
    translation.save()
  File "/app/network-api/networkapi/wagtailpages/pagemodels/products.py", line 204, in save
    super().save(*args, **kwargs)
  File "/app/.heroku/python/lib/python3.7/site-packages/django/db/models/base.py", line 754, in save
    force_update=force_update, update_fields=update_fields)
  File "/app/.heroku/python/lib/python3.7/site-packages/django/db/models/base.py", line 792, in save_base
    force_update, using, update_fields,
  File "/app/.heroku/python/lib/python3.7/site-packages/django/db/models/base.py", line 873, in _save_table
    forced_update)
  File "/app/.heroku/python/lib/python3.7/site-packages/django/db/models/base.py", line 926, in _do_update
    return filtered._update(values) > 0
  File "/app/.heroku/python/lib/python3.7/site-packages/django/db/models/query.py", line 803, in _update
    return query.get_compiler(self.db).execute_sql(CURSOR)
  File "/app/.heroku/python/lib/python3.7/site-packages/django/db/models/sql/compiler.py", line 1522, in execute_sql
    cursor = super().execute_sql(result_type)
  File "/app/.heroku/python/lib/python3.7/site-packages/django/db/models/sql/compiler.py", line 1156, in execute_sql
    cursor.execute(sql, params)
  File "/app/.heroku/python/lib/python3.7/site-packages/sentry_sdk/integrations/django/__init__.py", line 500, in execute
    return real_execute(self, sql, params)
  File "/app/.heroku/python/lib/python3.7/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/app/.heroku/python/lib/python3.7/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/app/.heroku/python/lib/python3.7/site-packages/scout_apm/django/instruments/sql.py", line 59, in db_execute_hook
    return execute(sql, params, many, context)
  File "/app/.heroku/python/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/app/.heroku/python/lib/python3.7/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/app/.heroku/python/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.DataError: value too long for type character varying(50)

```

**Comment by benhohner** [comment]
Look for wagtail widget that prevents categories over 50'
@kristinashu thoughts on providing UI notice that the users needs a shorter category, as opposed to increasing character limit (because categories might wrap or look bad on front end)?

**Comment by kristinashu** [comment]
I forget what the percentage is but I think we like to accommodate for translations to be up to 20% longer in length than in English. Theo can try to reduce the length but if the name starts to become unhelpful or inaccurate then increasing the character limit seems like the only option. Do you know where the UI might break with longer names?

**Comment by TheoChevalier** [comment]
> I forget what the percentage is but I think we like to accommodate for translations to be up to 20% longer in length than in English. Theo can try to reduce the length but if the name starts to become unhelpful or inaccurate then increasing the character limit seems like the only option. Do you know where the UI might break with longer names?

+1, I generally recommend ~30%, especially when French & German are involved.
For instance in `Smart Glasses & AR Headsets`, AR needs to be fully spelled `Augmented Reality` in French, there’s no acronym yet, which adds to the length: `Lunettes connectées et casques de réalité augmentée`

With this type of content, there’s generally little room for shortening the translation and I think it’s preferable to avoid using truncations.

**Comment by benhohner** [comment]
@kristinashu @TheoChevalier @pomax Ok, perhaps the best course of action is to increase the character limit to 100 characters and put a soft limit in the Wagtail admin dashboard of 50 characters using the character limiting custom widget?

**Comment by kristinashu** [comment]
Sounds good to me.

**Comment by jamilasnell** [comment]
@TheoChevalier Just checking in, is this something that you will be actioning on? Or is this something the other devs will do?
