### ISSUE TITLE
Some PNI product pages are crashing

### ISSUE THREAD

**Issue by TheoChevalier** [mozilla/foundation.mozilla.org#7814]
Some pages are crashing (in all languages) with the following:
`django.urls.exceptions.NoReverseMatch: Reverse for 'category-view' with arguments '('',)' not found. 1 pattern(s) tried: ['categories/(?P<slug>[\\w\\W]+)/']`

https://foundation.mozilla.org/en/privacynotincluded/samsung-galaxy-active-2/
https://foundation.mozilla.org/en/privacynotincluded/apple-watch-6/

```
2021-11-09T10:54:25.311533+00:00 heroku[router]: at=info method=GET path="/en/privacynotincluded/samsung-galaxy-active-2/" 
2021-11-09T10:54:25.297999+00:00 app[web.1]: Internal Server Error: /en/privacynotincluded/samsung-galaxy-active-2/

2021-11-09T10:54:25.298007+00:00 app[web.1]: Traceback (most recent call last):

2021-11-09T10:54:25.298008+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/django/core/handlers/exception.py", line 47, in inner

2021-11-09T10:54:25.298008+00:00 app[web.1]:     response = get_response(request)

2021-11-09T10:54:25.298009+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/django/core/handlers/base.py", line 204, in _get_response

2021-11-09T10:54:25.298009+00:00 app[web.1]:     response = response.render()

2021-11-09T10:54:25.298009+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/django/template/response.py", line 105, in render

2021-11-09T10:54:25.298010+00:00 app[web.1]:     self.content = self.rendered_content

2021-11-09T10:54:25.298011+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/sentry_sdk/integrations/django/templates.py", line 73, in rendered_content

2021-11-09T10:54:25.298011+00:00 app[web.1]:     return real_rendered_content.fget(self)

2021-11-09T10:54:25.298012+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/django/template/response.py", line 83, in rendered_content

2021-11-09T10:54:25.298013+00:00 app[web.1]:     return template.render(context, self._request)

2021-11-09T10:54:25.298013+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/django/template/backends/django.py", line 61, in render

2021-11-09T10:54:25.298013+00:00 app[web.1]:     return self.template.render(context)

2021-11-09T10:54:25.298014+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/scout_apm/core/stacktracer.py", line 25, in wrapper

2021-11-09T10:54:25.298014+00:00 app[web.1]:     return wrapped(*args, **kwargs)

2021-11-09T10:54:25.298015+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/django/template/base.py", line 170, in render

2021-11-09T10:54:25.298015+00:00 app[web.1]:     return self._render(context)

2021-11-09T10:54:25.298015+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/django/template/base.py", line 162, in _render

2021-11-09T10:54:25.298016+00:00 app[web.1]:     return self.nodelist.render(context)

2021-11-09T10:54:25.298016+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/django/template/base.py", line 938, in render

2021-11-09T10:54:25.298016+00:00 app[web.1]:     bit = node.render_annotated(context)

2021-11-09T10:54:25.298017+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/django/template/base.py", line 905, in render_annotated

2021-11-09T10:54:25.298017+00:00 app[web.1]:     return self.render(context)

2021-11-09T10:54:25.298018+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/django/template/loader_tags.py", line 150, in render

2021-11-09T10:54:25.298018+00:00 app[web.1]:     return compiled_parent._render(context)

2021-11-09T10:54:25.298018+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/django/template/base.py", line 162, in _render

2021-11-09T10:54:25.298019+00:00 app[web.1]:     return self.nodelist.render(context)

2021-11-09T10:54:25.298019+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/django/template/base.py", line 938, in render

2021-11-09T10:54:25.298019+00:00 app[web.1]:     bit = node.render_annotated(context)

2021-11-09T10:54:25.298019+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/django/template/base.py", line 905, in render_annotated

2021-11-09T10:54:25.298020+00:00 app[web.1]:     return self.render(context)

2021-11-09T10:54:25.298020+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/django/template/loader_tags.py", line 150, in render

2021-11-09T10:54:25.298020+00:00 app[web.1]:     return compiled_parent._render(context)

2021-11-09T10:54:25.298021+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/django/template/base.py", line 162, in _render

2021-11-09T10:54:25.298021+00:00 app[web.1]:     return self.nodelist.render(context)

2021-11-09T10:54:25.298021+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/django/template/base.py", line 938, in render

2021-11-09T10:54:25.298021+00:00 app[web.1]:     bit = node.render_annotated(context)

2021-11-09T10:54:25.298022+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/django/template/base.py", line 905, in render_annotated

2021-11-09T10:54:25.298022+00:00 app[web.1]:     return self.render(context)

2021-11-09T10:54:25.298022+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/scout_apm/core/stacktracer.py", line 25, in wrapper

2021-11-09T10:54:25.298022+00:00 app[web.1]:     return wrapped(*args, **kwargs)

2021-11-09T10:54:25.298022+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/django/template/loader_tags.py", line 62, in render

2021-11-09T10:54:25.298023+00:00 app[web.1]:     result = block.nodelist.render(context)

2021-11-09T10:54:25.298023+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/django/template/base.py", line 938, in render

2021-11-09T10:54:25.298023+00:00 app[web.1]:     bit = node.render_annotated(context)

2021-11-09T10:54:25.298023+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/django/template/base.py", line 905, in render_annotated

2021-11-09T10:54:25.298024+00:00 app[web.1]:     return self.render(context)

2021-11-09T10:54:25.298024+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/scout_apm/core/stacktracer.py", line 25, in wrapper

2021-11-09T10:54:25.298024+00:00 app[web.1]:     return wrapped(*args, **kwargs)

2021-11-09T10:54:25.298024+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/django/template/loader_tags.py", line 62, in render

2021-11-09T10:54:25.298024+00:00 app[web.1]:     result = block.nodelist.render(context)

2021-11-09T10:54:25.298025+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/django/template/base.py", line 938, in render

2021-11-09T10:54:25.298025+00:00 app[web.1]:     bit = node.render_annotated(context)

2021-11-09T10:54:25.298025+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/django/template/base.py", line 905, in render_annotated

2021-11-09T10:54:25.298025+00:00 app[web.1]:     return self.render(context)

2021-11-09T10:54:25.298030+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/django/template/defaulttags.py", line 516, in render

2021-11-09T10:54:25.298030+00:00 app[web.1]:     return self.nodelist.render(context)

2021-11-09T10:54:25.298030+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/django/template/base.py", line 938, in render

2021-11-09T10:54:25.298030+00:00 app[web.1]:     bit = node.render_annotated(context)

2021-11-09T10:54:25.298031+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/django/template/base.py", line 905, in render_annotated

2021-11-09T10:54:25.298031+00:00 app[web.1]:     return self.render(context)

2021-11-09T10:54:25.298031+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/django/template/defaulttags.py", line 211, in render

2021-11-09T10:54:25.298031+00:00 app[web.1]:     nodelist.append(node.render_annotated(context))

2021-11-09T10:54:25.298031+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/django/template/base.py", line 905, in render_annotated

2021-11-09T10:54:25.298032+00:00 app[web.1]:     return self.render(context)

2021-11-09T10:54:25.298032+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/django/template/defaulttags.py", line 516, in render

2021-11-09T10:54:25.298032+00:00 app[web.1]:     return self.nodelist.render(context)

2021-11-09T10:54:25.298032+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/django/template/base.py", line 938, in render

2021-11-09T10:54:25.298032+00:00 app[web.1]:     bit = node.render_annotated(context)

2021-11-09T10:54:25.298032+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/django/template/base.py", line 905, in render_annotated

2021-11-09T10:54:25.298032+00:00 app[web.1]:     return self.render(context)

2021-11-09T10:54:25.298033+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/django/template/library.py", line 192, in render

2021-11-09T10:54:25.298033+00:00 app[web.1]:     output = self.func(*resolved_args, **resolved_kwargs)

2021-11-09T10:54:25.298033+00:00 app[web.1]:   File "/app/network-api/networkapi/wagtailpages/templatetags/localization.py", line 78, in localizedroutablepageurl

2021-11-09T10:54:25.298033+00:00 app[web.1]:     routablepageurl(context, page, url_name, *args, **kwargs)

2021-11-09T10:54:25.298034+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/wagtail/contrib/routable_page/templatetags/wagtailroutablepage_tags.py", line 26, in routablepageurl

2021-11-09T10:54:25.298034+00:00 app[web.1]:     routed_url = page.reverse_subpage(url_name, args=args, kwargs=kwargs)

2021-11-09T10:54:25.298034+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/wagtail/contrib/routable_page/models.py", line 84, in reverse_subpage

2021-11-09T10:54:25.298034+00:00 app[web.1]:     return self.get_resolver().reverse(name, *args, **kwargs)

2021-11-09T10:54:25.298035+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/django/urls/resolvers.py", line 611, in reverse

2021-11-09T10:54:25.298035+00:00 app[web.1]:     return self._reverse_with_prefix(lookup_view, '', *args, **kwargs)

2021-11-09T10:54:25.298035+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/django/urls/resolvers.py", line 685, in _reverse_with_prefix

2021-11-09T10:54:25.298036+00:00 app[web.1]:     raise NoReverseMatch(msg)

2021-11-09T10:54:25.298036+00:00 app[web.1]: django.urls.exceptions.NoReverseMatch: Reverse for 'category-view' with arguments '('',)' not found. 1 pattern(s) tried: ['categories/(?P<slug>[\\w\\W]+)/']
```

**Comment by TheoChevalier** [comment]
I think it’s due to the "Fitness Trackers" category name being deleted, and some published pages were still using it
