### ISSUE TITLE
[PNI] Localized homepage & category pages are crashing

### ISSUE THREAD

**Issue by TheoChevalier** [mozilla/foundation.mozilla.org#7858]
Opening a localized category page is crashing, e.g. https://foundation.mozilla.org/fr/privacynotincluded/categories/gaming-platforms/

This includes the homepage https://foundation.mozilla.org/fr/privacynotincluded/ 

Production logs:
```
2021-11-15T09:45:35.517692+00:00 app[web.1]: Internal Server Error: /fr/privacynotincluded/categories/gaming-platforms/

2021-11-15T09:45:35.517703+00:00 app[web.1]: Traceback (most recent call last):

2021-11-15T09:45:35.517704+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/django/core/handlers/exception.py", line 47, in inner

2021-11-15T09:45:35.517704+00:00 app[web.1]:     response = get_response(request)

2021-11-15T09:45:35.517706+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/django/core/handlers/base.py", line 181, in _get_response

2021-11-15T09:45:35.517706+00:00 app[web.1]:     response = wrapped_callback(request, *callback_args, **callback_kwargs)

2021-11-15T09:45:35.517707+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/sentry_sdk/integrations/django/views.py", line 67, in sentry_wrapped_callback

2021-11-15T09:45:35.517707+00:00 app[web.1]:     return callback(request, *args, **kwargs)

2021-11-15T09:45:35.517708+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/contextlib.py", line 74, in inner

2021-11-15T09:45:35.517709+00:00 app[web.1]:     return func(*args, **kwds)

2021-11-15T09:45:35.517709+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/wagtail/core/views.py", line 26, in serve

2021-11-15T09:45:35.517709+00:00 app[web.1]:     return page.serve(request, *args, **kwargs)

2021-11-15T09:45:35.517709+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/wagtail/contrib/routable_page/models.py", line 121, in serve

2021-11-15T09:45:35.517710+00:00 app[web.1]:     return view(request, *args, **kwargs)

2021-11-15T09:45:35.517710+00:00 app[web.1]:   File "/app/network-api/networkapi/wagtailpages/pagemodels/products.py", line 1591, in categories_page

2021-11-15T09:45:35.517711+00:00 app[web.1]:     language_code=language_code

2021-11-15T09:45:35.517711+00:00 app[web.1]:   File "/app/network-api/networkapi/wagtailpages/pagemodels/products.py", line 105, in get_product_subset

2021-11-15T09:45:35.517711+00:00 app[web.1]:     products = sort_average(products)

2021-11-15T09:45:35.517712+00:00 app[web.1]:   File "/app/network-api/networkapi/wagtailpages/pagemodels/products.py", line 113, in sort_average

2021-11-15T09:45:35.517712+00:00 app[web.1]:     return sorted(products, key=lambda p: p.creepiness)

2021-11-15T09:45:35.517713+00:00 app[web.1]:   File "/app/network-api/networkapi/wagtailpages/pagemodels/products.py", line 113, in <lambda>

2021-11-15T09:45:35.517713+00:00 app[web.1]:     return sorted(products, key=lambda p: p.creepiness)

2021-11-15T09:45:35.517714+00:00 app[web.1]:   File "/app/network-api/networkapi/wagtailpages/pagemodels/products.py", line 725, in creepiness

2021-11-15T09:45:35.517714+00:00 app[web.1]:     product = self.original_product

2021-11-15T09:45:35.517714+00:00 app[web.1]:   File "/app/network-api/networkapi/wagtailpages/pagemodels/products.py", line 702, in original_product

2021-11-15T09:45:35.517714+00:00 app[web.1]:     return get_original_by_slug(ProductPage, self.slug)

2021-11-15T09:45:35.517714+00:00 app[web.1]:   File "/app/network-api/networkapi/wagtailpages/utils.py", line 442, in get_original_by_slug

2021-11-15T09:45:35.517715+00:00 app[web.1]:     return Model.objects.get(slug=slug, locale=DEFAULT_LOCALE_ID)

2021-11-15T09:45:35.517715+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/django/db/models/manager.py", line 85, in manager_method

2021-11-15T09:45:35.517715+00:00 app[web.1]:     return getattr(self.get_queryset(), name)(*args, **kwargs)

2021-11-15T09:45:35.517715+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/django/db/models/query.py", line 431, in get

2021-11-15T09:45:35.517715+00:00 app[web.1]:     self.model._meta.object_name

2021-11-15T09:45:35.517716+00:00 app[web.1]: networkapi.wagtailpages.pagemodels.products.ProductPage.DoesNotExist: ProductPage matching query does not exist.
```

**Comment by TheoChevalier** [comment]
About pages are affected too https://foundation.mozilla.org/fr/privacynotincluded/about/why/
