### ISSUE TITLE
Can’t translate PNI Mental Health Apps category snippet

### ISSUE THREAD

**Issue by TheoChevalier** [mozilla/foundation.mozilla.org#8621]
I’m hitting a 500 error when translating this snippet: https://foundation.mozilla.org/cms/localize/submit/snippet/wagtailpages/buyersguideproductcategory/217/

From the log below, it’s not entirely clear whether it’s a bug on our site or in Wagtail-localize.

```
2022-05-03T15:18:08.845125+00:00 app[web.5]: Internal Server Error: /cms/localize/submit/snippet/wagtailpages/buyersguideproductcategory/217/

2022-05-03T15:18:08.845133+00:00 app[web.5]: Traceback (most recent call last):

2022-05-03T15:18:08.845133+00:00 app[web.5]:   File "/app/.heroku/python/lib/python3.9/site-packages/wagtail_localize/models.py", line 733, in create_or_update_translation

2022-05-03T15:18:08.845134+00:00 app[web.5]:     translation = self.get_translated_instance(locale)

2022-05-03T15:18:08.845135+00:00 app[web.5]:   File "/app/.heroku/python/lib/python3.9/site-packages/wagtail_localize/models.py", line 497, in get_translated_instance

2022-05-03T15:18:08.845135+00:00 app[web.5]:     return self.specific_content_type.get_object_for_this_type(

2022-05-03T15:18:08.845136+00:00 app[web.5]:   File "/app/.heroku/python/lib/python3.9/site-packages/django/contrib/contenttypes/models.py", line 175, in get_object_for_this_type

2022-05-03T15:18:08.845136+00:00 app[web.5]:     return self.model_class()._base_manager.using(self._state.db).get(**kwargs)

2022-05-03T15:18:08.845137+00:00 app[web.5]:   File "/app/.heroku/python/lib/python3.9/site-packages/django/db/models/query.py", line 435, in get

2022-05-03T15:18:08.845137+00:00 app[web.5]:     raise self.model.DoesNotExist(

2022-05-03T15:18:08.845137+00:00 app[web.5]: networkapi.wagtailpages.pagemodels.products.BuyersGuideProductCategory.DoesNotExist: BuyersGuideProductCategory matching query does not exist.

2022-05-03T15:18:08.845138+00:00 app[web.5]: 

2022-05-03T15:18:08.845138+00:00 app[web.5]: During handling of the above exception, another exception occurred:

2022-05-03T15:18:08.845139+00:00 app[web.5]: 

2022-05-03T15:18:08.845139+00:00 app[web.5]: Traceback (most recent call last):

2022-05-03T15:18:08.845139+00:00 app[web.5]:   File "/app/.heroku/python/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner

2022-05-03T15:18:08.845139+00:00 app[web.5]:     response = get_response(request)

2022-05-03T15:18:08.845139+00:00 app[web.5]:   File "/app/.heroku/python/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response

2022-05-03T15:18:08.845140+00:00 app[web.5]:     response = wrapped_callback(request, *callback_args, **callback_kwargs)

2022-05-03T15:18:08.845140+00:00 app[web.5]:   File "/app/.heroku/python/lib/python3.9/site-packages/sentry_sdk/integrations/django/views.py", line 67, in sentry_wrapped_callback

2022-05-03T15:18:08.845140+00:00 app[web.5]:     return callback(request, *args, **kwargs)

2022-05-03T15:18:08.845140+00:00 app[web.5]:   File "/app/.heroku/python/lib/python3.9/contextlib.py", line 79, in inner

2022-05-03T15:18:08.845141+00:00 app[web.5]:     return func(*args, **kwds)

2022-05-03T15:18:08.845141+00:00 app[web.5]:   File "/app/.heroku/python/lib/python3.9/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func

2022-05-03T15:18:08.845142+00:00 app[web.5]:     response = view_func(request, *args, **kwargs)

2022-05-03T15:18:08.845142+00:00 app[web.5]:   File "/app/.heroku/python/lib/python3.9/site-packages/wagtail/admin/urls/__init__.py", line 125, in wrapper

2022-05-03T15:18:08.845142+00:00 app[web.5]:     return view_func(request, *args, **kwargs)

2022-05-03T15:18:08.845142+00:00 app[web.5]:   File "/app/.heroku/python/lib/python3.9/site-packages/wagtail/admin/auth.py", line 174, in decorated_view

2022-05-03T15:18:08.845142+00:00 app[web.5]:     response = view_func(request, *args, **kwargs)

2022-05-03T15:18:08.845143+00:00 app[web.5]:   File "/app/.heroku/python/lib/python3.9/site-packages/django/views/generic/base.py", line 70, in view

2022-05-03T15:18:08.845143+00:00 app[web.5]:     return self.dispatch(request, *args, **kwargs)

2022-05-03T15:18:08.845143+00:00 app[web.5]:   File "/app/.heroku/python/lib/python3.9/site-packages/wagtail_localize/views/submit_translations.py", line 242, in dispatch

2022-05-03T15:18:08.845143+00:00 app[web.5]:     return super().dispatch(request, *args, **kwargs)

2022-05-03T15:18:08.845143+00:00 app[web.5]:   File "/app/.heroku/python/lib/python3.9/site-packages/django/views/generic/base.py", line 98, in dispatch

2022-05-03T15:18:08.845144+00:00 app[web.5]:     return handler(request, *args, **kwargs)

2022-05-03T15:18:08.845144+00:00 app[web.5]:   File "/app/.heroku/python/lib/python3.9/site-packages/wagtail_localize/views/submit_translations.py", line 190, in post

2022-05-03T15:18:08.845144+00:00 app[web.5]:     return self.form_valid(form)

2022-05-03T15:18:08.845144+00:00 app[web.5]:   File "/app/.heroku/python/lib/python3.9/contextlib.py", line 79, in inner

2022-05-03T15:18:08.845144+00:00 app[web.5]:     return func(*args, **kwds)

2022-05-03T15:18:08.845145+00:00 app[web.5]:   File "/app/.heroku/python/lib/python3.9/site-packages/wagtail_localize/views/submit_translations.py", line 198, in form_valid

2022-05-03T15:18:08.845145+00:00 app[web.5]:     translator.create_translations(self.object)

2022-05-03T15:18:08.845145+00:00 app[web.5]:   File "/app/.heroku/python/lib/python3.9/site-packages/wagtail_localize/views/submit_translations.py", line 139, in create_translations

2022-05-03T15:18:08.845145+00:00 app[web.5]:     translation.save_target(user=self.user)

2022-05-03T15:18:08.845145+00:00 app[web.5]:   File "/app/.heroku/python/lib/python3.9/site-packages/wagtail_localize/models.py", line 1322, in save_target

2022-05-03T15:18:08.845146+00:00 app[web.5]:     self.source.create_or_update_translation(

2022-05-03T15:18:08.845146+00:00 app[web.5]:   File "/app/.heroku/python/lib/python3.9/site-packages/wagtail_localize/models.py", line 740, in create_or_update_translation

2022-05-03T15:18:08.845146+00:00 app[web.5]:     translation = original.copy_for_translation(locale)

2022-05-03T15:18:08.845146+00:00 app[web.5]:   File "/app/.heroku/python/lib/python3.9/site-packages/wagtail/core/models/i18n.py", line 177, in copy_for_translation

2022-05-03T15:18:08.845146+00:00 app[web.5]:     translated, child_object_map = _copy(self)

2022-05-03T15:18:08.845146+00:00 app[web.5]:   File "/app/.heroku/python/lib/python3.9/site-packages/wagtail/core/models/copying.py", line 83, in _copy

2022-05-03T15:18:08.845146+00:00 app[web.5]:     target = source.__class__(**data_dict)

2022-05-03T15:18:08.845147+00:00 app[web.5]:   File "/app/network-api/networkapi/wagtailpages/pagemodels/mixin/snippets.py", line 9, in __init__

2022-05-03T15:18:08.845153+00:00 app[web.5]:     super().__init__(*args, **kwargs)

2022-05-03T15:18:08.845153+00:00 app[web.5]:   File "/app/.heroku/python/lib/python3.9/site-packages/django/db/models/base.py", line 498, in __init__

2022-05-03T15:18:08.845153+00:00 app[web.5]:     _setattr(self, prop, kwargs[prop])

2022-05-03T15:18:08.845153+00:00 app[web.5]:   File "/app/.heroku/python/lib/python3.9/site-packages/django/db/models/fields/related_descriptors.py", line 545, in __set__

2022-05-03T15:18:08.845154+00:00 app[web.5]:     raise TypeError(

2022-05-03T15:18:08.845154+00:00 app[web.5]: TypeError: Direct assignment to the reverse side of a related set is prohibited. Use +.set() instead.
```

**Comment by tbrlpld** [comment]
@TheoChevalier Is this only this particular category or all Buyer's Guide Categories?

**Comment by TheoChevalier** [comment]
It did happen with both the Mental Health Apps and Reproductive Health Apps categories, but I tried again today, and the issue is gone!
It probably got fixed along the way, I was able to finally translate these two and all their sub-categories.

So, we might be able to close this ticket?

**Comment by tbrlpld** [comment]
@TheoChevalier Yup, if you are not experiencing this issue anymore we can close it 👍

@cdanfon If we close this I might need other tickets for the sprint.
