### ISSUE TITLE
Can’t edit localized homepages

### ISSUE THREAD

**Issue by TheoChevalier** [mozilla/foundation.mozilla.org#8657]
Editing a localized homepage returns a 500 error: https://foundation.mozilla.org/cms/pages/3710/edit/ (French homepage)

```
2022-05-12T13:00:39.088727+00:00 app[web.2]: Internal Server Error: /cms/pages/3710/edit/

2022-05-12T13:00:39.088737+00:00 app[web.2]: Traceback (most recent call last):

2022-05-12T13:00:39.088738+00:00 app[web.2]:   File "/app/.heroku/python/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner

2022-05-12T13:00:39.088738+00:00 app[web.2]:     response = get_response(request)

2022-05-12T13:00:39.088739+00:00 app[web.2]:   File "/app/.heroku/python/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response

2022-05-12T13:00:39.088739+00:00 app[web.2]:     response = wrapped_callback(request, *callback_args, **callback_kwargs)

2022-05-12T13:00:39.088742+00:00 app[web.2]:   File "/app/.heroku/python/lib/python3.9/site-packages/sentry_sdk/integrations/django/views.py", line 67, in sentry_wrapped_callback

2022-05-12T13:00:39.088743+00:00 app[web.2]:     return callback(request, *args, **kwargs)

2022-05-12T13:00:39.088743+00:00 app[web.2]:   File "/app/.heroku/python/lib/python3.9/contextlib.py", line 79, in inner

2022-05-12T13:00:39.088744+00:00 app[web.2]:     return func(*args, **kwds)

2022-05-12T13:00:39.088744+00:00 app[web.2]:   File "/app/.heroku/python/lib/python3.9/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func

2022-05-12T13:00:39.088745+00:00 app[web.2]:     response = view_func(request, *args, **kwargs)

2022-05-12T13:00:39.088745+00:00 app[web.2]:   File "/app/.heroku/python/lib/python3.9/site-packages/wagtail/admin/urls/__init__.py", line 125, in wrapper

2022-05-12T13:00:39.088746+00:00 app[web.2]:     return view_func(request, *args, **kwargs)

2022-05-12T13:00:39.088746+00:00 app[web.2]:   File "/app/.heroku/python/lib/python3.9/site-packages/wagtail/admin/auth.py", line 174, in decorated_view

2022-05-12T13:00:39.088746+00:00 app[web.2]:     response = view_func(request, *args, **kwargs)

2022-05-12T13:00:39.088747+00:00 app[web.2]:   File "/app/.heroku/python/lib/python3.9/site-packages/django/views/generic/base.py", line 70, in view

2022-05-12T13:00:39.088747+00:00 app[web.2]:     return self.dispatch(request, *args, **kwargs)

2022-05-12T13:00:39.088747+00:00 app[web.2]:   File "/app/.heroku/python/lib/python3.9/site-packages/wagtail/admin/views/pages/edit.py", line 304, in dispatch

2022-05-12T13:00:39.088748+00:00 app[web.2]:     response = self.run_hook('before_edit_page', self.request, self.page)

2022-05-12T13:00:39.088748+00:00 app[web.2]:   File "/app/.heroku/python/lib/python3.9/site-packages/wagtail/admin/views/generic/hooks.py", line 16, in run_hook

2022-05-12T13:00:39.088748+00:00 app[web.2]:     result = fn(*args, **kwargs)

2022-05-12T13:00:39.088749+00:00 app[web.2]:   File "/app/.heroku/python/lib/python3.9/site-packages/wagtail_localize/wagtail_hooks.py", line 259, in before_edit_page

2022-05-12T13:00:39.088749+00:00 app[web.2]:     return edit_translation.edit_translation(request, translation, page)

2022-05-12T13:00:39.088749+00:00 app[web.2]:   File "/app/.heroku/python/lib/python3.9/site-packages/wagtail_localize/views/edit_translation.py", line 657, in edit_translation

2022-05-12T13:00:39.088749+00:00 app[web.2]:     location_info = get_segment_location_info(

2022-05-12T13:00:39.088750+00:00 app[web.2]:   File "/app/.heroku/python/lib/python3.9/site-packages/wagtail_localize/views/edit_translation.py", line 451, in get_segment_location_info

2022-05-12T13:00:39.088750+00:00 app[web.2]:     "widget": widget_from_field(child_field) if widget else None,

2022-05-12T13:00:39.088750+00:00 app[web.2]:   File "/app/.heroku/python/lib/python3.9/site-packages/wagtail_localize/views/edit_translation.py", line 306, in widget_from_field

2022-05-12T13:00:39.088751+00:00 app[web.2]:     for model in edit_handler.target_models()

2022-05-12T13:00:39.088751+00:00 app[web.2]: AttributeError: 'NoneType' object has no attribute 'target_models'
```

**Comment by TheoChevalier** [comment]
This has been fixed by the Wagtail 3.0 upgrade
