### ISSUE TITLE
[PNI] Translating content categories leads to server error

### ISSUE THREAD

**Issue by tbrlpld** [mozilla/foundation.mozilla.org#9757]
## Description

This is a follow up to #9563. 

When trying to translate a buyer's guide content category a server error occurs. 

To reproduce:

* Visit the admin
* Go to the "buyer's guide content category" snippet screen
* Create a new category
* Try to translate the newly created category
* See error

```

Traceback (most recent call last):
  File "/app/dockerpythonvenv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/app/dockerpythonvenv/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.9/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/app/dockerpythonvenv/lib/python3.9/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/app/dockerpythonvenv/lib/python3.9/site-packages/wagtail/admin/urls/__init__.py", line 125, in wrapper
    return view_func(request, *args, **kwargs)
  File "/app/dockerpythonvenv/lib/python3.9/site-packages/wagtail/admin/auth.py", line 195, in decorated_view
    return view_func(request, *args, **kwargs)
  File "/app/dockerpythonvenv/lib/python3.9/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/app/dockerpythonvenv/lib/python3.9/site-packages/wagtail_localize/views/submit_translations.py", line 242, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/app/dockerpythonvenv/lib/python3.9/site-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/app/dockerpythonvenv/lib/python3.9/site-packages/wagtail_localize/views/submit_translations.py", line 190, in post
    return self.form_valid(form)
  File "/usr/local/lib/python3.9/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/app/dockerpythonvenv/lib/python3.9/site-packages/wagtail_localize/views/submit_translations.py", line 216, in form_valid
    single_translated_object = self.object.get_translation(
  File "/app/dockerpythonvenv/lib/python3.9/site-packages/wagtail/core/models/i18n.py", line 152, in get_translation
    return self.get_translations(inclusive=True).get(locale_id=pk(locale))
  File "/app/dockerpythonvenv/lib/python3.9/site-packages/django/db/models/query.py", line 435, in get
    raise self.model.DoesNotExist(

Exception Type: DoesNotExist at /cms/localize/submit/snippet/wagtailpages/buyersguidecontentcategory/4/
Exception Value: BuyersGuideContentCategory matching query does not exist.
```

I suspect this error has something to do with the unique constraint on the slug and the fact that all values are copied to the translation when the translation is first created. 

## Expected bahavior

Category can be translated

**Comment by tbrlpld** [comment]
This seems related: https://github.com/wagtail/wagtail-localize/issues/484

**Comment by tbrlpld** [comment]
@TheoChevalier @cdanfon This should be ready for testing.

**Comment by cdanfon** [comment]
Hey @tbrlpld tested and working as expected on staging. Moving this to 'Ready for prod'

**Comment by TheoChevalier** [comment]
Looks good to me as well, thanks!
